import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createDeviceStore} from './device-integration-store.mjs';
const u={id:'u',tenantId:'t'},stationId='station-1';
function fixture(fn){const dir=mkdtempSync(join(tmpdir(),'devices-'));try{fn(join(dir,'jobs.csv'));}finally{rmSync(dir,{recursive:true,force:true});}}
const cmd=(action,extra={})=>({action,stationId,operationId:'op-'+action,...extra});const enqueue=extra=>cmd('enqueue',{deviceId:'browser',recordId:'INV-1',capability:'receipt',copies:1,...extra});
test('queue is persisted with exact idempotency and changed payload conflicts',()=>fixture(file=>{const s=createDeviceStore(file),first=s.handle(u,'p',enqueue()).body;assert.ok(first.id);assert.equal(createDeviceStore(file).handle(u,'p',enqueue()).body.id,first.id);assert.equal(s.handle(u,'p',enqueue({copies:2})).status,409);}));
test('scope isolates tenant, product, user and workstation jobs',()=>fixture(file=>{const s=createDeviceStore(file),j=s.handle(u,'p',enqueue()).body;for(const [user,product,station] of [[{...u,tenantId:'x'},'p',stationId],[{...u,id:'x'},'p',stationId],[u,'x',stationId],[u,'p','other']]){assert.equal(s.handle(user,product,{action:'library',stationId:station}).body.jobs.length,0);assert.equal(s.handle(user,product,cmd('dispatch',{jobId:j.id,stationId:station}),true).status,404);}}));
test('lookup preserves contexts and returns only exact backend records',()=>fixture(file=>{const s=createDeviceStore(file);assert.equal(s.handle(u,'p',cmd('lookup',{code:' 8901234567890 ',context:'pos'})).body.id,'ITEM-1');assert.equal(s.handle(u,'p',cmd('lookup',{code:'8901234567890',context:'purchase'})).status,404);assert.equal(s.handle(u,'p',cmd('lookup',{code:'x'.repeat(257),context:'pos'})).status,400);}));
test('tenant policies require admin, version checks and enforce user locks',()=>fixture(file=>{const s=createDeviceStore(file),policy={version:1,automatic:false,lockedDevice:'demo-label',maxCopies:2};assert.equal(s.handle(u,'p',cmd('policy',{policy})).status,403);assert.equal(s.handle(u,'p',cmd('policy',{policy}),true).body.version,2);assert.equal(s.handle(u,'p',cmd('policy',{operationId:'stale',policy}),true).status,409);assert.equal(s.handle(u,'p',cmd('preference',{deviceId:'browser'})).status,403);assert.equal(s.handle(u,'p',enqueue()).status,400);assert.equal(s.handle(u,'p',enqueue({capability:'label',copies:3})).status,400);}));
test('browser dispatch means requested, demo means simulated, native stays queued',()=>fixture(file=>{const s=createDeviceStore(file);for(const [deviceId,status] of [['browser','print-requested'],['demo-receipt','simulated'],['native','queued']]){const j=s.handle(u,'p',enqueue({operationId:deviceId,deviceId})).body;const r=s.handle(u,'p',cmd('dispatch',{operationId:'send-'+deviceId,jobId:j.id}));assert.equal(r.status,deviceId==='native'?503:200);assert.equal(s.handle(u,'p',cmd('library')).body.jobs.find(x=>x.id===j.id).status,status);if(deviceId!=='native')assert.equal(s.handle(u,'p',cmd('dispatch',{operationId:'again-'+deviceId,jobId:j.id})).status,409);}}));
test('dispatch applies policy changed after enqueue and cancelled jobs stay cancelled',()=>fixture(file=>{const s=createDeviceStore(file),j=s.handle(u,'p',enqueue()).body;s.handle(u,'p',cmd('policy',{policy:{version:1,automatic:false,lockedDevice:'demo-label',maxCopies:10}}),true);assert.equal(s.handle(u,'p',cmd('dispatch',{jobId:j.id})).status,403);assert.equal(s.handle(u,'p',cmd('cancel',{jobId:j.id})).body.status,'cancelled');assert.equal(s.handle(u,'p',cmd('dispatch',{jobId:j.id})).status,409);}));
test('automatic event simulation is admin-only, opt-in and deduplicated by event ID',()=>fixture(file=>{const s=createDeviceStore(file),event=cmd('event',{eventId:'sale-1',event:'sale.completed',recordId:'ITEM-1'});assert.equal(s.handle(u,'p',event,true).status,403);s.handle(u,'p',cmd('policy',{policy:{version:1,automatic:true,lockedDevice:'',maxCopies:10}}),true);assert.equal(s.handle(u,'p',event).status,403);const j=s.handle(u,'p',event,true).body;assert.equal(j.status,'simulated');assert.equal(s.handle(u,'p',{...event,operationId:'new-retry'},true).body.id,j.id);assert.equal(s.handle(u,'p',{...event,recordId:'ITEM-2',operationId:'changed-event'},true).status,409);assert.equal(s.handle(u,'p',cmd('library')).body.jobs.length,1);}));
test('routing validates device capability and rejects stale policy versions',()=>fixture(file=>{const s=createDeviceStore(file),rule={id:'sale',event:'sale.completed',capability:'receipt',deviceId:'demo-label',enabled:true};assert.equal(s.handle(u,'p',cmd('rule',{rule,version:1}),true).status,400);assert.equal(s.handle(u,'p',cmd('rule',{rule:{...rule,deviceId:'browser'},version:1}),true).status,200);assert.equal(s.handle(u,'p',cmd('rule',{operationId:'stale',rule,version:1}),true).status,409);}));
