import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createIdentityStore} from './identity-device-store.mjs';
const user={id:'u',tenantId:'t'},stationId='station';const cmd=(action,extra={})=>({action,stationId,operationId:action,...extra});const start=extra=>cmd('start',{deviceId:'demo-eid',patientId:'DEMO-P1',consent:true,...extra});function fixture(fn){const dir=mkdtempSync(join(tmpdir(),'identity-'));try{fn(join(dir,'identity.csv'));}finally{rmSync(dir,{recursive:true,force:true});}}
test('document read persists synthetic fields but never authenticates or changes patient',()=>fixture(file=>{const s=createIdentityStore(file),a=s.handle(user,'app',start()).body;const r=s.handle(user,'app',cmd('simulate',{attemptId:a.id,scenarioId:'match'})).body;assert.equal(r.status,'demo-match');assert.equal(r.authenticated,false);assert.equal(r.document.reference,'DEMO-DOC-001');assert.equal(createIdentityStore(file).handle(user,'app',cmd('library')).body.attempts[0].id,a.id);}));
test('request scope isolates tenant, application, patient binding, owner and station',()=>fixture(file=>{const s=createIdentityStore(file),a=s.handle(user,'app',start()).body;for(const [u,p,station] of [[{...user,tenantId:'other'},'app',stationId],[{...user,id:'other'},'app',stationId],[user,'other',stationId],[user,'app','other']])assert.equal(s.handle(u,p,cmd('simulate',{attemptId:a.id,scenarioId:'match',stationId:station}),true).status,404);assert.equal(s.handle(user,'app',cmd('simulate',{attemptId:a.id,patientId:'DEMO-P2',scenarioId:'match'})).status,409);}));
test('retries are idempotent, changed requests conflict and a fresh completion cannot replay',()=>fixture(file=>{const s=createIdentityStore(file),a=s.handle(user,'app',start()).body;assert.equal(s.handle(user,'app',start()).body.id,a.id);assert.equal(s.handle(user,'app',start({patientId:'DEMO-P2'})).status,409);const complete=cmd('simulate',{attemptId:a.id,scenarioId:'mismatch'});assert.equal(s.handle(user,'app',complete).body.status,'demo-mismatch');assert.equal(s.handle(user,'app',complete).body.id,a.id);assert.equal(s.handle(user,'app',{...complete,operationId:'new'}).status,409);}));
test('expired challenges are rejected including result replay',()=>fixture(file=>{let now=new Date('2026-09-10T12:00:00Z');const s=createIdentityStore(file,()=>now),a=s.handle(user,'app',start()).body;const complete=cmd('simulate',{attemptId:a.id,scenarioId:'match'});s.handle(user,'app',complete);now=new Date('2026-09-10T12:03:00Z');assert.equal(s.handle(user,'app',complete).status,409);}));
test('biometrics default off, admin policy and current lock apply to pending capture',()=>fixture(file=>{const s=createIdentityStore(file),bio=start({deviceId:'demo-fingerprint'});assert.equal(s.handle(user,'app',bio).status,403);const policy={version:1,biometricsEnabled:true,lockedDevice:''};assert.equal(s.handle(user,'app',cmd('policy',{policy})).status,403);assert.equal(s.handle(user,'app',cmd('policy',{policy}),true).status,200);const a=s.handle(user,'app',bio).body;s.handle(user,'app',cmd('policy',{operationId:'disable',policy:{...policy,version:2,biometricsEnabled:false}}),true);assert.equal(s.handle(user,'app',cmd('simulate',{attemptId:a.id,scenarioId:'match'})).status,403);}));
test('no capture without consent; native transport unavailable and raw biometric data rejected',()=>fixture(file=>{const s=createIdentityStore(file);assert.equal(s.handle(user,'app',start({consent:false})).status,400);assert.equal(s.handle(user,'app',start({deviceId:'native-passport'})).status,503);assert.equal(s.handle(user,'app',start({fingerprintTemplate:'sensitive'})).status,400);s.handle(user,'app',start());assert.equal(readFileSync(file,'utf8').includes('sensitive'),false);}));
test('manual review works when biometrics are disabled and never sets authenticated',()=>fixture(file=>{const s=createIdentityStore(file),r=s.handle(user,'app',cmd('manual',{patientId:'DEMO-P1'}));assert.equal(r.status,200);assert.equal(r.body.status,'manual-review');assert.equal(r.body.authenticated,false);}));
test('cancel stops capture, only one active request allowed, expired document is distinct',()=>fixture(file=>{const s=createIdentityStore(file),a=s.handle(user,'app',start()).body;assert.equal(s.handle(user,'app',start({operationId:'second'})).status,409);s.handle(user,'app',cmd('cancel',{attemptId:a.id}));assert.equal(s.handle(user,'app',cmd('simulate',{attemptId:a.id,scenarioId:'match'})).status,409);const b=s.handle(user,'app',start({operationId:'third'})).body;assert.equal(s.handle(user,'app',cmd('simulate',{operationId:'expired-doc',attemptId:b.id,scenarioId:'expired'})).body.status,'demo-expired-document');}));
