import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createLabelStore} from './label-printing-store.mjs';
const user={id:'user-a',tenantId:'tenant-a'};
function fixture(fn){const dir=mkdtempSync(join(tmpdir(),'label-test-'));try{fn(join(dir,'labels.csv'));}finally{rmSync(dir,{recursive:true,force:true});}}
const create=(operationId='create')=>({action:'create',operationId,templateId:'sample-code128',profileId:'sheet-a4',recordIds:['SAMPLE-1','SAMPLE-2'],copies:2});
test('backend generates real SVG symbols and persists exact retry identity',()=>fixture(file=>{const s=createLabelStore(file);const a=s.handle(user,'nexora',create());assert.equal(a.status,200);assert.equal(a.body.labels.length,2);assert.match(Buffer.from(a.body.labels[0].image.split(',')[1],'base64').toString(),/<svg.*viewBox=/);assert.equal(createLabelStore(file).handle(user,'nexora',create()).body.id,a.body.id);assert.equal(s.handle(user,'nexora',{...create(),copies:3}).status,409);}));
test('rejects over-copies, incompatible stock, missing IDs and cross-category records',()=>fixture(file=>{const s=createLabelStore(file);for(const patch of [{copies:101},{profileId:'wristband',templateId:'payment-link',recordIds:['INV-1'],copies:1},{recordIds:['missing']},{recordIds:['PATIENT-1']}])assert.equal(s.handle(user,'nexora',{...create(),...patch}).status,400);}));
test('tenant, application and user isolation with server-only admin authority',()=>fixture(file=>{const s=createLabelStore(file),job=s.handle(user,'nexora',create()).body;for(const [u,app] of [[{...user,tenantId:'other'},'nexora'],[user,'other'],[{...user,id:'other'},'nexora']])assert.equal(s.handle(u,app,{action:'job',jobId:job.id}).status,404);assert.equal(s.handle({...user,id:'other'},'nexora',{action:'job',jobId:job.id},true).status,200);assert.equal(s.handle(user,'nexora',{action:'policy',operationId:'p',policy:{version:1,maxCopies:1,reprintAllowed:false,lockedProfile:''}}).status,403);}));
test('print attempts are not completion; reprint reason and policy are enforced',()=>fixture(file=>{const s=createLabelStore(file),job=s.handle(user,'nexora',create()).body;assert.equal(s.handle(user,'nexora',{action:'print',operationId:'p1',jobId:job.id}).body.attempts[0].status,'requested');assert.equal(s.handle(user,'nexora',{action:'print',operationId:'p2',jobId:job.id}).status,403);assert.equal(s.handle(user,'nexora',{action:'print',operationId:'p3',jobId:job.id,reason:'Damaged label'}).body.attempts.length,2);s.handle(user,'nexora',{action:'policy',operationId:'pol',policy:{version:1,maxCopies:1,reprintAllowed:false,lockedProfile:'sheet-a4'}},true);assert.equal(s.handle(user,'nexora',{action:'print',operationId:'p4',jobId:job.id,reason:'Damaged label'}).status,403);assert.equal(s.handle(user,'nexora',{action:'preference',operationId:'pref',profileId:'label-roll'}).status,403);}));
test('payment QR never marks paid on creation or print and expires server-side',()=>fixture(file=>{let now=new Date('2026-09-10T12:00:00Z');const s=createLabelStore(file,()=>now);const job=s.handle(user,'nexora',{...create(),templateId:'payment-link',recordIds:['INV-1'],copies:1}).body;assert.equal(job.paymentStatus,'pending');assert.match(job.labels[0].code,/example.invalid/);assert.equal(s.handle(user,'nexora',{action:'simulate',operationId:'sim',jobId:job.id,paymentStatus:'paid'}).status,403);assert.equal(s.handle(user,'nexora',{action:'print',operationId:'first-print',jobId:job.id}).status,200);now=new Date('2026-09-10T12:06:00Z');assert.equal(s.handle(user,'nexora',{action:'print',operationId:'first-print',jobId:job.id}).status,409);assert.equal(s.handle(user,'nexora',{action:'job',jobId:job.id}).body.paymentStatus,'expired');assert.equal(s.handle(user,'nexora',{action:'print',operationId:'p',jobId:job.id}).status,409);}));
test('all advertised symbologies render; administrator simulation is explicit',()=>fixture(file=>{const s=createLabelStore(file),lib=s.handle(user,'nexora',{action:'library'}).body;for(const template of lib.templates){const record=lib.records.find(r=>r.category===template.category);const result=s.handle(user,'nexora',{...create(template.id),templateId:template.id,profileId:template.category==='patient'?'wristband':'sheet-a4',recordIds:[record.id],copies:1});assert.equal(result.status,200,template.id);if(template.category==='payment')assert.equal(s.handle(user,'nexora',{action:'simulate',operationId:'sim-'+template.id,jobId:result.body.id,paymentStatus:'paid'},true).body.paymentStatus,'paid');}}));
test('stock fit failure identifies the printer field',()=>fixture(file=>{const result=createLabelStore(file).handle(user,'nexora',{...create(),templateId:'payment-static',profileId:'wristband',recordIds:['INV-1'],copies:1});assert.equal(result.status,400);assert.deepEqual(result.body.fieldErrors,{profileId:'labels.fit'});}));
