import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:net';
test('authenticated HTTP record lifecycle, isolation and conflicts', async t => {
  const portServer = createServer(); await new Promise(r => portServer.listen(0, '127.0.0.1', r));
  const port = portServer.address().port; await new Promise(r => portServer.close(r));
  const dir = mkdtempSync(join(tmpdir(), 'record-api-'));
  const child = spawn(process.execPath, [new URL('./server.mjs', import.meta.url).pathname], { env: { ...process.env, PORT: String(port), RECORD_DATA_DIR: dir, NEXORA_DATA_DIR: dir }, stdio: 'ignore' });
  t.after(async () => { child.kill(); await new Promise(r => child.once('exit', r)); rmSync(dir, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${port}`;
  for (let i=0;i<100;i++) { try { await fetch(base); break; } catch { await new Promise(r=>setTimeout(r,50)); } }
  const login = async username => (await (await fetch(base+'/auth/login', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ username, password:username }) })).json()).token;
  const one = await login('user1'), two = await login('user2');
  const key = JSON.stringify(['nexora', 'http-test:customer:new']);
  const path = '/records/'+encodeURIComponent(key);
  const request = (token, suffix='', body) => fetch(base+path+suffix, { method:body?'PUT':'GET', headers:{ Authorization:`Bearer ${token}`, 'Content-Type':'application/json' }, ...(body?{body:JSON.stringify(body)}:{}) });
  assert.equal((await request('invalid')).status,401);
  assert.equal((await request(one,'/draft',{ values:{name:'draft'}, version:0, baseVersion:0, operationId:'draft1' })).status,200);
  assert.equal((await (await request(two)).json()).draft,null);
  const destinationKey=JSON.stringify(['nexora','http-test:customer:generated']);
  const created=await request(one,'/create',{ values:{name:'created'}, version:0, draftVersion:1, destinationKey, operationId:'create1' });
  assert.equal(created.status,200);
  const list=await fetch(base+'/records?scope='+encodeURIComponent(JSON.stringify(['nexora','http-test:customer:'])),{headers:{Authorization:`Bearer ${two}`}});
  assert.equal((await list.json()).records[0].record.values.name,'created');
  assert.equal((await request(one,'/draft',{ values:{name:'stale'}, version:1, baseVersion:0, operationId:'draft2' })).status,409);
  const post = (path, body) => fetch(base+path,{method:'POST',headers:{Authorization:`Bearer ${two}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
  const search = {pageId:'customer-master',title:'Customer Master',entity:'customer',productId:'http-test',pageSize:10,sort:{key:'id',direction:'desc'}};
  const first = await (await post('/worklists/search',search)).json();
  const second = await (await post('/worklists/search',{...search,page:2})).json();
  assert.equal(first.rows.length,10);assert.equal(second.rows.length,10);assert.equal(first.total,second.total);
  assert.equal(first.rows.some(a=>second.rows.some(b=>a.id===b.id)),false);
  assert.equal(first.rows[0].id > first.rows[9].id,true);
  const id=first.rows.find(row=>row.status!=='Locked').id;
  const archived=await (await post('/worklists/archive',{...search,ids:[id,'missing']})).json();
  assert.deepEqual(archived.results.map(item=>item.ok),[true,false]);
  const refreshed=await (await post('/worklists/search',search)).json();assert.equal(refreshed.total,first.total-1);
  assert.equal(refreshed.rows.some(row=>row.id===id),false);
  const filtered=await (await post('/worklists/search',{...search,sensitiveFilters:{query:second.rows[0].id},queryMode:'exact',page:99})).json();
  assert.equal(filtered.total,1);assert.equal(filtered.page,1);
  const invalidKey=encodeURIComponent(JSON.stringify(['nexora','form:customer-master:test']));
  const invalid=await fetch(base+'/records/'+invalidKey,{method:'PUT',headers:{Authorization:`Bearer ${two}`,'Content-Type':'application/json'},body:JSON.stringify({values:{legalName:''},version:0,draftVersion:0,operationId:'invalid'})});
  assert.equal(invalid.status,422);assert.ok((await invalid.json()).fieldErrors.legalName);
  const panelScope=['http-test','customer-master','CUS-02401'];
  const panels=(token,body)=>fetch(base+'/record-panels',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({scope:panelScope,...body})});
  const comment=await panels(one,{action:'comment',text:'HTTP panel comment',operationId:'http-comment'});assert.equal(comment.status,200);
  const again=await (await panels(one,{action:'comment',text:'HTTP panel comment',operationId:'http-comment'})).json();assert.equal(again.comments.length,1);
  const readOnly=await (await panels(two,{action:'list'})).json();assert.equal(readOnly.comments.length,1);assert.equal(readOnly.permissions.write,false);
  assert.equal((await panels(two,{action:'comment',text:'denied',operationId:'denied-comment'})).status,403);
  assert.equal((await panels(one,{action:'link',pageId:'customer-master',recordId:'missing',label:'Missing',operationId:'missing-link'})).status,404);
  assert.equal((await panels(one,{scope:['http-test','missing','A'],action:'list'})).status,404);
  const upload=await (await panels(one,{action:'upload',name:'demo.txt',content:'ZGVtbw==',operationId:'http-upload'})).json();
  assert.equal(upload.attachments[0].content,undefined);
  const download=await (await panels(one,{action:'download',id:upload.attachments[0].id})).json();assert.equal(download.content,'ZGVtbw==');
  const imports=(token,body)=>fetch(base+'/imports',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
  const importId=crypto.randomUUID();
  const importBody={action:'preview',id:importId,productId:'http-test',pageId:'customer-master',rows:[{customerCode:'HTTP-IMPORT',legalName:'Imported Customer',customerType:'Corporate',contactName:'Test Contact',email:'test@example.com',address1:'Test Street',city:'Dubai'}]};
  assert.equal((await imports(two,importBody)).status,403);
  const preview=await (await imports(one,importBody)).json();assert.equal(preview.job.rows[0].status,'pending');assert.equal(preview.job.confirmed,false);
  const confirmed=await (await imports(one,{action:'run',id:importId})).json();assert.equal(confirmed.job.rows[0].status,'success');
  const repeated=await (await imports(one,{action:'run',id:importId,retry:true})).json();assert.equal(repeated.job.rows[0].recordId,confirmed.job.rows[0].recordId);
  const duplicate=await (await imports(one,{...importBody,id:crypto.randomUUID()})).json();assert.equal(duplicate.job.rows[0].status,'invalid');assert.match(duplicate.job.rows[0].errors.customerCode,/already exists/);
  const importedSearch=await (await post('/worklists/search',{...search,sensitiveFilters:{query:'Imported Customer'}})).json();assert.equal(importedSearch.total,1);
  const approvals=(token,body)=>fetch(base+'/approvals',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({scope:['http-test','customer-master'],operationId:crypto.randomUUID(),...body})});
  assert.equal((await approvals('invalid',{action:'read'})).status,401);
  const submitted=await (await approvals(two,{action:'submit',recordId:'CUS-02401',version:0,comment:'HTTP approval request'})).json();assert.equal(submitted.items[0].status,'pending');
  const decision=await (await approvals(one,{action:'decide',items:[{recordId:'CUS-02401',version:1}],decision:'approve',comment:'Verified HTTP record'})).json();assert.equal(decision.results[0].ok,true);
  const requesterNotices=await (await approvals(two,{action:'read'})).json();assert.equal(requesterNotices.notifications[0].message,'Approved');
  await fetch(base+'/auth/logout',{method:'POST',headers:{Authorization:`Bearer ${one}`}});
  assert.equal((await request(one)).status,401);
});
