'use client';
import React from 'react';
import {useDraggable} from '@dnd-kit/core';
import {useSortable} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
import {Button,Card,CardHeader,CardTitle,CardContent,Input,Select,Textarea,Checkbox,useLocalization} from '@pepbits/ops-ui';
import type {TemplateField,TemplateSection} from '@pepbits/erp-config';
export function DesignerPanel({title,children}:{title:string;children:React.ReactNode}){return <Card><CardHeader><CardTitle title={title}/></CardHeader><CardContent className="space-y-3">{children}</CardContent></Card>;}
export function PaletteItem({type,disabled,add}:{type:TemplateField['type'];disabled:boolean;add:()=>void}){const {t}=useLocalization(),d=useDraggable({id:'palette:'+type,disabled});return <div ref={d.setNodeRef} className="flex gap-2"><Button disabled={disabled} onClick={add} className="flex-1">{t('designer.type.'+type)}</Button><Button disabled={disabled} ref={d.setActivatorNodeRef} {...d.attributes} {...d.listeners} style={{touchAction:'none'}} aria-roledescription={t('designer.drag')} aria-label={t('designer.drag')+' '+t('designer.type.'+type)}>⠿</Button></div>;}
export function SortableItem({id,label,disabled,selected,select,up,down,children}:{id:string;label:string;disabled:boolean;selected:boolean;select:()=>void;up?:()=>void;down?:()=>void;children?:React.ReactNode}){const {t}=useLocalization(),s=useSortable({id,disabled});return <div ref={s.setNodeRef} style={{transform:CSS.Transform.toString(s.transform)}} ><Card className="p-3"><div className="flex items-center gap-2"><Button ref={s.setActivatorNodeRef} disabled={disabled} {...s.attributes} {...s.listeners} style={{touchAction:'none'}} aria-roledescription={t('designer.drag')} aria-label={t('designer.drag')+' '+label}>⠿</Button><Button variant={selected?'primary':'secondary'} className="min-w-0 flex-1" onClick={select}>{label}</Button><Button disabled={disabled||!up} onClick={up} aria-label={t('designer.up')+' '+label}>↑</Button><Button disabled={disabled||!down} onClick={down} aria-label={t('designer.down')+' '+label}>↓</Button></div>{children}</Card></div>;}
export function FieldProperties({field,sectionId,sections,disabled,change,move,remove,duplicate}:{field:TemplateField;sectionId:string;sections:TemplateSection[];disabled:boolean;change:(f:TemplateField)=>void;move:(id:string)=>void;remove:()=>void;duplicate:()=>void}){const {t}=useLocalization();return <DesignerPanel title="designer.properties"><Input label={t('designer.id')} value={field.id} readOnly/><Input label={t('designer.label')} value={t(field.label)} disabled={disabled} onChange={e=>change({...field,label:e.target.value})}/><Checkbox label={t('designer.required')} checked={!!field.required} disabled={disabled} onChange={e=>change({...field,required:e.target.checked})}/><Select label={t('designer.section')} value={sectionId} disabled={disabled} options={sections.map(s=>({value:s.id,label:s.title}))} onChange={e=>move(e.target.value)}/>{field.type==='number'&&<Input type="number" label={t('designer.minimum')} value={field.min??''} disabled={disabled} onChange={e=>change({...field,min:e.target.value===''?undefined:Number(e.target.value)})}/>}{field.type==='select'&&<Textarea label={t('designer.options')} value={field.options?.map(o=>o.value+'|'+o.label).join('\n')??''} disabled={disabled} onChange={e=>change({...field,options:e.target.value.split('\n').map(line=>{const i=line.indexOf('|');return {value:i<0?line:line.slice(0,i),label:i<0?line:line.slice(i+1)};})})}/>}<div className="flex flex-wrap gap-2"><Button disabled={disabled} onClick={duplicate}>{t('designer.duplicate')}</Button><Button disabled={disabled} onClick={remove}>{t('designer.remove')}</Button></div></DesignerPanel>;}
