'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Button,Select,Modal,TableContainer,Table,TableHeader,TableBody,TableRow,TableHead,TableCell,RecoveryNotice,failureFromError,useLocalization} from '@pepbits/ops-ui';
import {resolveDesignerCatalog,resolveDesignerValues,localizeDesignerDefinition,matchesDesignerCondition,designerOptions,changeDesignerValue,type DesignerRuntime,type DesignerCatalog,type DesignerValues,type DesignerCommand,type DesignerAnswer} from '@pepbits/erp-config';
import type {DesignerAdapter} from '@pepbits/erp-data';
import {DesignerSections} from './sections';
import {type TemplateFieldState} from '../templates/template-parts';
export function RuntimePanel({runtime,catalog,adapter,close}:{runtime:DesignerRuntime;catalog:DesignerCatalog;adapter:DesignerAdapter;close:()=>void}){
 const {t,language,dateTime}=useLocalization(),[history,setHistory]=useState<DesignerAnswer[]>([]),[historyOpen,setHistoryOpen]=useState(false),[releaseId,setRelease]=useState(''),[entityId,setEntity]=useState(''),[answer,setAnswer]=useState<DesignerAnswer|null>(null),[values,setValues]=useState<DesignerValues>({}),[errors,setErrors]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[loaded,setLoaded]=useState(false),[failure,setFailure]=useState<unknown>(null),[discard,setDiscard]=useState(false);
 const lock=useRef(false),active=useRef(true),retry=useRef<DesignerCommand|null>(null);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const release=runtime.releases.find(r=>r.id===releaseId),definition=release?resolveDesignerCatalog(release.definition,catalog):null,effective=definition?resolveDesignerValues(definition,values):values;
 const states:Record<string,TemplateFieldState>={};if(definition)for(const f of definition.sections.flatMap(s=>s.fields)){const lookup=f.type==='select'?designerOptions(localizeDesignerDefinition(definition,language),f.id,effective):null;states[f.id]={options:lookup?.options,disabled:!!f.rules?.calculation||!!(f.rules?.readOnlyWhen&&matchesDesignerCondition(f.rules.readOnlyWhen,effective))||lookup?.state==='missing-parent'};}
 async function send(command:DesignerCommand){if(lock.current)return;lock.current=true;setBusy(true);setFailure(null);retry.current=command;
  try{const result=await adapter.command(command);if(!active.current)return;setErrors(result.validation??{});if(result.validation&&Object.keys(result.validation).length&&command.action==='answer-submit')return;const next=result.runtime?.answer??null;setAnswer(next);setHistory(result.runtime?.answerHistory??[]);setValues(next?.values??{});setLoaded(true);setDirty(false);retry.current=null;}catch(e){if(active.current)setFailure(e);}finally{lock.current=false;if(active.current)setBusy(false);}}
 function context(kind:'release'|'entity',value:string){if(dirty||busy)return;if(kind==='release'){setRelease(value);setEntity('');}else setEntity(value);setLoaded(false);setHistory([]);setAnswer(null);setValues({});setErrors({});setFailure(null);retry.current=null;}
 return <Modal open onClose={()=>dirty?setDiscard(true):!busy&&close()} title={t('designer.runtime')} size="xl"><div className="space-y-4 p-4"><p>{t('designer.runtimeHelp')}</p>
 {discard&&<div><p>{t('designer.discardWarning')}</p><Button onClick={close}>{t('designer.discard')}</Button><Button onClick={()=>setDiscard(false)}>{t('designer.keep')}</Button></div>}
 {!!failure&&<RecoveryNotice failure={failureFromError(failure)} onRetry={()=>{if(retry.current)void send(retry.current);}}/>}
 <Select label={t('designer.release')} value={releaseId} disabled={busy||dirty} options={runtime.releases.map(r=>({value:r.id,label:t(r.definition.title)+' · '+r.version+(r.retired?' · '+t('designer.status.retired'):'')}))} onChange={e=>context('release',e.target.value)}/>
 <Select label={t('designer.owner')} value={entityId} disabled={busy||dirty} options={runtime.entities.filter(e=>e.entityType===release?.definition.binding?.entityType).map(e=>({value:e.id,label:t(e.label)+' · '+e.id}))} onChange={e=>context('entity',e.target.value)}/>
 <Button disabled={busy||dirty||!entityId||!releaseId} onClick={()=>void send({action:'runtime-load',releaseId,entityId})}>{t('designer.loadAnswer')}</Button>
 {loaded&&definition&&<><p role="status">{t(answer?.status==='submitted'?'designer.answerSubmitted':'designer.answerDraft')}</p><DesignerSections definition={definition} values={effective} states={states} errors={Object.fromEntries(Object.entries(errors).map(([k,v])=>[k,t(v)]))} disabled={busy||answer?.status==='submitted'||release?.retired} change={(id,v)=>{setValues(changeDesignerValue(definition,values,id,v));setDirty(true);setErrors({});retry.current=null;}}/>
 <div className="flex flex-wrap gap-2">{(['answer-save','answer-submit'] as const).map(action=><Button key={action} disabled={busy||answer?.status==='submitted'||release?.retired} onClick={()=>void send({action,releaseId,entityId,answerRevision:answer?.revision??0,values,operationId:crypto.randomUUID()})}>{t('designer.'+action)}</Button>)}<Button disabled={busy||!dirty} onClick={()=>{setValues(answer?.values??{});setDirty(false);setErrors({});retry.current=null;}}>{t('designer.discard')}</Button></div></>}
 <Button disabled={!history.length} onClick={()=>setHistoryOpen(!historyOpen)}>{t('designer.answerHistory')}</Button>{historyOpen&&<TableContainer><Table><TableHeader><TableRow>{['version','actor','savedAt','status'].map(k=><TableHead key={k}>{t('designer.history.'+k)}</TableHead>)}</TableRow></TableHeader><TableBody>{history.slice().reverse().map(h=><TableRow key={h.revision}><TableCell>{h.revision}</TableCell><TableCell>{h.updatedBy}</TableCell><TableCell>{dateTime(h.updatedAt)}</TableCell><TableCell>{t(h.status==='submitted'?'designer.answerSubmitted':'designer.answerDraft')}</TableCell></TableRow>)}</TableBody></Table></TableContainer>}
 </div></Modal>;
}
