'use client';
import React,{useState,useEffect,useRef} from 'react';
import {DndContext,PointerSensor,KeyboardSensor,useSensor,useSensors,closestCenter,type DragEndEvent} from '@dnd-kit/core';
import {SortableContext,rectSortingStrategy,verticalListSortingStrategy,sortableKeyboardCoordinates,arrayMove} from '@dnd-kit/sortable';
import {Button,Input,Select,Checkbox,PresentationProvider,RecoveryNotice,failureFromError,useLocalization} from '@pepbits/ops-ui';
import {effectivePreferences,cloneDesignerSections,resolveDesignerCatalog,isDesignerDefinition,validDesignerDependencies,designerOptions,designerDescendants,changeDesignerValue,type DesignerDefinition,type DesignerView,type TemplateField,type DesignerField,type TemplateValue,type DesignerValue,type DesignerValues,type DesignerCommand} from '@pepbits/erp-config';
import type {DesignerAdapter} from '@pepbits/erp-data';
import type {PreferenceHost} from '../preference-choice';
import {LabelProperties} from './label-properties';
import {DesignerPreview} from './preview';
import {ReleaseComparison} from './release-comparison';
import {LifecyclePanel} from './lifecycle-panel';
import {RuntimePanel} from './runtime-panel';
import {CatalogManager} from './catalog-manager';
import {Eye,ArrowLeft} from 'lucide-react';
import {DesignerPanel,PaletteItem,SortableItem,FieldProperties} from './components';
import styles from './designer.module.css';
export interface DcpDesignerProps extends PreferenceHost{adapter:DesignerAdapter;scopeKey:string}
export function DcpDesignerWorkspace(props:DcpDesignerProps){const preferences=props.preferencePolicy?effectivePreferences(props.preferences,props.preferencePolicy):props.preferences;return <PresentationProvider value={preferences}><Controller key={props.scopeKey} {...props} preferences={preferences}/></PresentationProvider>;}
function Controller({adapter,preferences}:DcpDesignerProps){const {t,dateTime}=useLocalization(),[view,setView]=useState<DesignerView|null>(null),[definition,setDefinition]=useState<DesignerDefinition|null>(null),[selected,setSelected]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),[preview,setPreview]=useState(false),[runtimeOpen,setRuntimeOpen]=useState(false),[catalogOpen,setCatalogOpen]=useState(false),[values,setValues]=useState<DesignerValues>({}),[errors,setErrors]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[discard,setDiscard]=useState<string|null>(null);
 const pending=useRef<DesignerCommand|null>(null),locked=useRef(false),mounted=useRef(true);
 const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
 useEffect(()=>{mounted.current=true;let active=true;adapter.command({action:'load'}).then(v=>{if(active){setView(v);setDefinition(v.initial);setSelected(v.initial.sections[0].id);}}).catch(e=>{if(active)setError(e);});return()=>{active=false;mounted.current=false;};},[adapter]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function send(command:DesignerCommand){if(locked.current)return;locked.current=true;setBusy(true);setError(null);pending.current=command;try{const v=await adapter.command(command);if(!mounted.current)return;setView(v);setDefinition(v.record?.definition??v.initial);setSelected((v.record?.definition??v.initial).sections[0].id);setDirty(false);setErrors({});setValues({});setMessage(command.action==='save'?'designer.saved':'');pending.current=null;}catch(e){if(mounted.current)setError(e);}finally{locked.current=false;if(mounted.current)setBusy(false);}}
 if(!definition||!view)return <div>{error?<RecoveryNotice failure={failureFromError(error)} onRetry={()=>void send({action:'load'})}/>:<p role="status">{t('designer.loading')}</p>}</div>;
 const catalog=view.catalog??{sets:[],relationships:[]},resolved=resolveDesignerCatalog(definition,catalog);
 const disabled=busy||!view.canDesign||!!(view.record?.status&&view.record.status!=='draft'),section=definition.sections.find(s=>s.id===selected||s.fields.some(f=>f.id===selected))??definition.sections[0],field=section.fields.find(f=>f.id===selected);
 function edit(next:DesignerDefinition){if(disabled)return;setDefinition(next);setValues(previous=>{const fields=next.sections.flatMap(s=>s.fields),retained=Object.fromEntries(Object.entries(previous).filter(([id])=>fields.some(f=>f.id===id)));const resolvedNext=resolveDesignerCatalog(next,catalog);if(!resolvedNext)return retained;for(const f of fields)if(f.type==='select'&&retained[f.id]!==undefined&&!designerOptions(resolvedNext,f.id,retained).options.some(o=>o.value===retained[f.id])){delete retained[f.id];for(const id of designerDescendants(next,f.id))delete retained[id];}return retained;});setDirty(true);setMessage('');setErrors({});pending.current=null;}
 const updateField=(f:DesignerField)=>edit({...definition!,sections:definition!.sections.map(s=>({...s,fields:s.fields.map(x=>x.id===f.id?f:x)}))});
 function add(type:TemplateField['type'],target=section.id){if(!definition||disabled||definition.sections.reduce((n,s)=>n+s.fields.length,0)>=100)return;const f:TemplateField={id:'field_'+crypto.randomUUID().replaceAll('-',''),label:t('designer.type.'+type),type,...(type==='select'?{options:[{value:'option1',label:t('designer.option')}]}:{})};edit({...definition,sections:definition.sections.map(s=>s.id===target?{...s,fields:[...s.fields,f]}:s)});setSelected(f.id);}
 function reorder(id:string,target:string){if(!definition||disabled)return;const a=definition.sections.findIndex(s=>s.id===id),b=definition.sections.findIndex(s=>s.id===target);if(a>=0&&b>=0){edit({...definition,sections:arrayMove(definition.sections,a,b)});return;}const from=definition.sections.find(s=>s.fields.some(f=>f.id===id)),to=definition.sections.find(s=>s.id===target||s.fields.some(f=>f.id===target));if(!from||!to)return;const f=from.fields.find(f=>f.id===id)!;if(from===to){const targetIndex=to.fields.findIndex(f=>f.id===target);if(targetIndex>=0)edit({...definition,sections:definition.sections.map(s=>s.id===from.id?{...s,fields:arrayMove(s.fields,s.fields.indexOf(f),targetIndex)}:s)});}else edit({...definition,sections:definition.sections.map(s=>s.id===from.id?{...s,fields:s.fields.filter(x=>x.id!==id)}:s.id===to.id?{...s,fields:[...s.fields,f]}:s)});}
 const drop=({active,over}:DragEndEvent)=>{if(!over||disabled)return;const id=String(active.id);if(id.startsWith('palette:')){const target=definition.sections.find(s=>s.id===String(over.id)||s.fields.some(f=>f.id===String(over.id)));add(id.slice(8) as TemplateField['type'],target?.id);return;}reorder(id,String(over.id));};
 const count=definition.sections.reduce((n,s)=>n+s.fields.length,0);
 return <div className={styles.workspace} data-tour="dcp-designer" data-designer data-density={preferences.density}>
 <div className={styles.toolbar}><div><h1>{t('designer.title')}</h1><p>{t('designer.boundary')}</p></div><Button variant={preview?'secondary':'primary'} disabled={!preview&&(!isDesignerDefinition(definition)||!resolved||!isDesignerDefinition(resolved))} leftIcon={preview?<ArrowLeft size={16}/>:<Eye size={16}/>} aria-pressed={preview} onClick={()=>{setPreview(!preview);setMessage('');}}>{t(preview?'designer.design':'designer.preview')}</Button></div>
 {!!error&&<RecoveryNotice failure={failureFromError(error)} onRetry={()=>{if(pending.current)void send(pending.current);}} onReload={()=>setDiscard(view.record?.id??'')} onReturn={()=>setDiscard(view.record?.id??'')} />}
 {!view.canDesign&&<p role="status">{t('designer.denied')}</p>}
 {!preview&&<div className={styles.documentToolbar}><Input label={t('designer.formTitle')} value={t(definition.title)} disabled={disabled} onChange={e=>edit({...definition,title:e.target.value})}/><Select label={t('designer.restore')} value={view.record?.id??''} disabled={busy} options={[{value:'',label:t('designer.new')},...view.records.map(r=>({value:r.id,label:r.definition.title}))]} onChange={e=>{if(dirty)setDiscard(e.target.value);else void send({action:'load',id:e.target.value||undefined});}}/><Button disabled={disabled||!dirty} onClick={()=>{if(!isDesignerDefinition(definition)){setMessage('designer.invalid');return;}void send(pending.current?.action==='save'?pending.current:{action:'save',id:view.record?.id,revision:view.record?.revision,definition,operationId:crypto.randomUUID()});}}>{t('designer.save')}</Button></div>}
 {(!validDesignerDependencies(definition)||!resolved)&&<p role="alert">{t('designer.dependencyInvalid')}</p>}
 {discard!==null&&<DesignerPanel title="designer.unsaved"><p>{t('designer.discardWarning')}</p><Button onClick={()=>{void send({action:'load',id:discard||undefined});setDiscard(null);}}>{t('designer.discard')}</Button><Button onClick={()=>setDiscard(null)}>{t('designer.keep')}</Button></DesignerPanel>}
 <p className={styles.saveState} role="status">{message?t(message):dirty?t('designer.unsaved'):view.record?`${t('designer.saved')} · ${dateTime(view.record.updatedAt)}`:t('designer.initial')}</p>
 {preview?<DesignerPreview adapter={adapter} resolved={resolved??definition} definition={definition} values={values} errors={errors} change={(id,v)=>{setValues(changeDesignerValue(definition,values,id,v));setErrors({});setMessage('');}} reset={()=>{setValues({});setErrors({});setMessage('');}} validation={e=>{setErrors(e);setMessage(Object.keys(e).length?'designer.invalidValues':'designer.valid');}} clearValidation={()=>{setErrors({});setMessage('');}}/>:
 <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={drop} autoScroll={false} accessibility={{screenReaderInstructions:{draggable:t('designer.dragHelp')},announcements:{onDragStart:()=>t('designer.dragStart'),onDragOver:()=>t('designer.dragOver'),onDragEnd:()=>t('designer.dragEnd'),onDragCancel:()=>t('designer.dragCancel')}}}>
 <div className={styles.layout}><aside className={styles.palettePanel}><DesignerPanel title="designer.palette"><p>{t('designer.paletteHelp')}</p><div className={styles.palette}>{view.types.map(type=><PaletteItem key={type} type={type} disabled={disabled||count>=100} add={()=>add(type)}/>)}</div><Button onClick={()=>setRuntimeOpen(true)}>{t('designer.runtime')}</Button><Button onClick={()=>setCatalogOpen(true)}>{t('designer.catalogManage')}</Button>{view.examples?.map((example,index)=><Button key={index} disabled={disabled||definition.sections.length+example.sections.length>20||count+example.sections.reduce((n,s)=>n+s.fields.length,0)>100} onClick={()=>{const sections=cloneDesignerSections(example,()=> 'copy_'+crypto.randomUUID().replaceAll('-',''));edit({...definition,sections:[...definition.sections,...sections]});setSelected(sections[0].fields[0]?.id??sections[0].id);}}>{t(example.title)}</Button>)}<Button disabled={disabled||definition.sections.length>=20} onClick={()=>{const s={id:'section_'+crypto.randomUUID().replaceAll('-',''),title:t('designer.section'),fields:[]};edit({...definition,sections:[...definition.sections,s]});setSelected(s.id);}}>{t('designer.addSection')}</Button></DesignerPanel></aside>
 <div className={styles.canvas} style={{'--designer-columns':definition.columns} as React.CSSProperties}><SortableContext items={definition.sections.map(s=>s.id)} strategy={verticalListSortingStrategy}>{definition.sections.map((s,i)=><SortableItem key={s.id} id={s.id} label={t(s.title)} selected={selected===s.id} disabled={disabled} select={()=>setSelected(s.id)} up={i?()=>reorder(s.id,definition.sections[i-1].id):undefined} down={i<definition.sections.length-1?()=>reorder(s.id,definition.sections[i+1].id):undefined}><div className={styles.fields}><SortableContext items={s.fields.map(f=>f.id)} strategy={rectSortingStrategy}>{s.fields.map((f,j)=><SortableItem kind="field" key={f.id} id={f.id} label={t(f.label)} selected={selected===f.id} disabled={disabled} select={()=>setSelected(f.id)} up={j?()=>reorder(f.id,s.fields[j-1].id):undefined} down={j<s.fields.length-1?()=>reorder(f.id,s.fields[j+1].id):undefined}><span className={styles.meta}>{t('designer.type.'+f.type)}{f.required?' · '+t('designer.required'):''}</span></SortableItem>)}</SortableContext>{!s.fields.length&&<p>{t('designer.empty')}</p>}</div></SortableItem>)}</SortableContext></div>
 <aside className={styles.inspector}>{field?<FieldProperties catalog={catalog} parents={definition.sections.flatMap(s=>s.fields).filter(f=>f.type==='select'&&!!f.valueSet===!!field.valueSet&&f.id!==field.id&&!designerDescendants(definition,field.id).has(f.id))} hasChildren={designerDescendants(definition,field.id).size>0} field={field} sectionId={section.id} sections={definition.sections} disabled={disabled} change={updateField} move={id=>reorder(field.id,id)} duplicate={()=>{const f={...field,id:'field_'+crypto.randomUUID().replaceAll('-','')};if(count>=100)return;edit({...definition,sections:definition.sections.map(s=>s.id===section.id?{...s,fields:[...s.fields,f]}:s)});setSelected(f.id);}} remove={()=>{edit({...definition,sections:definition.sections.map(s=>({...s,fields:s.fields.filter(f=>f.id!==field.id)}))});setSelected(section.id);}}/>:<DesignerPanel title="designer.section"><Input label={t('designer.id')} value={section.id} readOnly/><Input label={t('designer.label')} value={t(section.title)} disabled={disabled} onChange={e=>edit({...definition,sections:definition.sections.map(s=>s.id===section.id?{...s,title:e.target.value}:s)})}/><Checkbox label={t('designer.repeatable')} checked={!!section.repeatable} disabled={disabled} onChange={e=>edit({...definition,sections:definition.sections.map(s=>s.id===section.id?{...s,repeatable:e.target.checked,minItems:undefined,maxItems:undefined}:s)})}/>{section.repeatable&&(['minItems','maxItems'] as const).map(k=><Input key={k} type="number" min={0} max={100} label={t('designer.'+k)} value={section[k]??(k==='minItems'?0:10)} disabled={disabled} onChange={e=>edit({...definition,sections:definition.sections.map(s=>s.id===section.id?{...s,[k]:Number(e.target.value)}:s)})}/>)}<LabelProperties labels={section.labels} disabled={disabled} change={labels=>edit({...definition,sections:definition.sections.map(s=>s.id===section.id?{...s,labels}:s)})}/><Button disabled={disabled||definition.sections.length===1||section.fields.length>0} onClick={()=>{edit({...definition,sections:definition.sections.filter(s=>s.id!==section.id)});setSelected(definition.sections.find(s=>s.id!==section.id)!.id);}}>{t('designer.removeEmpty')}</Button></DesignerPanel>}<DesignerPanel title="designer.lifecycle"><ReleaseComparison definition={definition} releases={(view.runtime?.releases??[]).filter(r=>r.recordId===view.record?.id)}/><LifecyclePanel record={view.record} entities={view.runtime?.entities??[]} definition={definition} change={edit} send={c=>{if(view.canDesign)void send(c);}} disabled={disabled} dirty={dirty||!view.canDesign} busy={busy}/></DesignerPanel></aside></div></DndContext>}
 {runtimeOpen&&view.runtime&&<RuntimePanel runtime={view.runtime} catalog={catalog} adapter={adapter} close={()=>setRuntimeOpen(false)}/>}
 <CatalogManager open={catalogOpen} close={()=>setCatalogOpen(false)} catalog={catalog} canDesign={view.canDesign} adapter={adapter} update={next=>setView(current=>current?{...current,catalog:next}:current)}/>
 </div>;
}
