'use client';
import { ERP } from '@/lib/mock';
import { usePrefsStore } from '@/lib/prefs/store';
import type { Preferences as P } from '@/lib/prefs/schema';
import { toast } from '@/lib/toast/store';
import { cn } from '@/lib/format';
import { Button } from '@/components/primitives/Button';
import { Select } from '@/components/primitives/Select';
import { Toggle } from '@/components/primitives/Toggle';
type Opt = [string | number, string];
function Seg<K extends keyof P>({ k, opts }: { k: K; opts: Opt[] }) { const { prefs, set } = usePrefsStore(); return <div className="flex border border-border rounded-ui overflow-hidden">{opts.map(([v, l]) => <button key={String(v)} onClick={() => set({ [k]: v } as Partial<P>)} className={cn('flex-1 h-[30px] text-xs whitespace-nowrap px-2 border-s border-border first:border-s-0', String(prefs[k]) === String(v) ? 'bg-accent text-accent-fg' : 'bg-surface')}>{l}</button>)}</div>; }
function Range<K extends keyof P>({ k, min, max, step, unit }: { k: K; min: number; max: number; step: number; unit: string }) { const { prefs, set } = usePrefsStore(); return <div className="flex items-center gap-2.5"><input type="range" min={min} max={max} step={step} value={Number(prefs[k])} onChange={e => set({ [k]: +e.target.value } as Partial<P>)} className="flex-1" /><span className="font-mono text-xs min-w-11 text-right">{String(prefs[k])}{unit}</span></div>; }
function Tog<K extends keyof P>({ k }: { k: K }) { const { prefs, set } = usePrefsStore(); return <Toggle checked={!!prefs[k]} labels={['On', 'Off']} onChange={v => set({ [k]: v } as Partial<P>)} />; }
function Sel<K extends keyof P>({ k, opts, numeric }: { k: K; opts: Opt[]; numeric?: boolean }) { const { prefs, set } = usePrefsStore(); return <Select value={String(prefs[k])} onChange={e => set({ [k]: numeric ? +e.target.value : e.target.value } as Partial<P>)} options={opts.map(([v, l]) => ({ value: String(v), label: l }))} />; }
const Row = ({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) => <div className="flex flex-col gap-1.5"><span className="text-[11.5px] text-muted">{label}</span>{children}{hint && <span className="text-[11px] text-muted leading-snug">{hint}</span>}</div>;
const Group = ({ title, hint, tour, children }: { title: string; hint: string; tour: string; children: React.ReactNode }) => <div data-tour={tour} className="bg-surface border border-border rounded-ui"><div className="px-4 py-2.5 border-b border-border flex gap-2.5 items-baseline"><span className="font-semibold">{title}</span><span className="text-muted text-xs">{hint}</span></div><div className="px-4 py-3.5 grid gap-x-[18px] gap-y-3.5" style={{ gridTemplateColumns: 'repeat(auto-fill,minmax(230px,1fr))' }}>{children}</div></div>;
export function Preferences() {
  const { prefs, set, reset } = usePrefsStore();
  return (
    <section className="flex flex-col gap-3.5 max-w-[1100px]">
      <div className="flex items-center gap-2.5 flex-wrap"><span className="text-muted text-[12.5px]">Changes apply instantly to every module and are stored for this browser.</span><span className="flex-1" /><Button variant="outline" tone="danger" onClick={() => { reset(); toast('Preferences reset to defaults', 'info'); }}>Reset to defaults</Button><Button onClick={() => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(prefs, null, 2)], { type: 'application/json' })); a.download = 'vantage-preferences.json'; a.click(); }}>Export JSON</Button></div>
      <div data-tour="prefs-theme" className="bg-surface border border-border rounded-ui"><div className="px-4 py-2.5 border-b border-border font-semibold">Theme</div>
        <div className="px-4 py-3.5 grid gap-2.5" style={{ gridTemplateColumns: 'repeat(auto-fill,minmax(150px,1fr))' }}>{Object.entries(ERP.themes).map(([id, th]) => <button key={id} onClick={() => set({ theme: id as P['theme'] })} className={cn('flex flex-col gap-2 p-2 border-2 rounded-ui text-left hover:border-accent', id === prefs.theme ? 'border-accent' : 'border-border')}>
          <span className="flex h-14 overflow-hidden" style={{ background: th.bg, border: '1px solid ' + th.border }}><span className="w-3.5" style={{ background: th.sidebar }} /><span className="flex-1 m-2 flex items-end p-1" style={{ background: th.surface, border: '1px solid ' + th.border }}><span className="w-[22px] h-2" style={{ background: th.accent }} /></span></span>
          <span className="flex justify-between items-center text-[12.5px]"><span>{th.name}</span>{id === prefs.theme && <span className="text-accent text-[11px]">✓ Active</span>}</span></button>)}</div></div>
      <Group title="Typography" hint="Fonts and sizes for the shell, forms and result lists" tour="prefs-type"><Row label="Font family"><Sel k="font" opts={ERP.fonts.map(f => [f.id, f.label])} /></Row><Row label="Base font size"><Range k="fs" min={11} max={16} step={0.5} unit="px" /></Row><Row label="Form field size"><Range k="fsForm" min={11} max={17} step={0.5} unit="px" /></Row><Row label="Result / table size"><Range k="fsResult" min={10} max={16} step={0.5} unit="px" /></Row><Row label="Density"><Seg k="density" opts={[['compact', 'Compact'], ['comfortable', 'Comfortable']]} /></Row><Row label="Corner radius"><Range k="corners" min={0} max={12} step={1} unit="px" /></Row></Group>
      <Group title="Layout" hint="Honoured by every module and page" tour="prefs-layout"><Row label="Sidebar position"><Seg k="sidebar" opts={[['left', 'Left'], ['right', 'Right']]} /></Row><Row label="Sidebar pinned open" hint="Otherwise expands on hover"><Tog k="pinned" /></Row><Row label="Record form style" hint="View, edit and new records"><Seg k="formLayout" opts={[['rail', 'Rail'], ['tabs', 'Tabs'], ['wizard', 'Wizard']]} /></Row><Row label="Worklist result view"><Seg k="resultView" opts={[['table', 'Table'], ['cards', 'Card grid']]} /></Row><Row label="Quick view style" hint="Shown when clicking a result row"><Sel k="quickView" opts={[['card', 'Centered record card'], ['modal', 'Center modal'], ['panel-left', 'Left side panel'], ['panel-right', 'Right side panel']]} /></Row><Row label="Default rows per page"><Sel k="pageSize" numeric opts={[[10, '10'], [20, '20'], [50, '50'], [100, '100']]} /></Row></Group>
      <Group title="Notifications (toasts)" hint="Save, post and error messages" tour="prefs-toast"><Row label="Position"><Sel k="toastPos" opts={[['top-left', 'Top left'], ['top-center', 'Top center'], ['top-right', 'Top right'], ['bottom-left', 'Bottom left'], ['bottom-center', 'Bottom center'], ['bottom-right', 'Bottom right']]} /></Row><Row label="Duration"><Range k="toastDur" min={1} max={12} step={1} unit="s" /></Row><Row label="Style"><Seg k="toastStyle" opts={[['solid', 'Solid'], ['light', 'Light']]} /></Row></Group>
      <Group title="Language & help" hint="Applies to menus, actions and messages" tour="prefs-lang"><Row label="Language" hint="Arabic switches the whole layout to right-to-left"><Sel k="lang" opts={Object.entries(ERP.i18n).map(([k, d]) => [k, d._name])} /></Row><Row label="Help assistant button" hint="Guided tours and shortcuts, bottom corner"><Tog k="help" /></Row><Row label="Documentation panel on pages"><Tog k="docs" /></Row><Row label="Documentation position"><Seg k="docsPos" opts={[['top', 'Top'], ['bottom', 'Bottom']]} /></Row><Row label="Animations"><Tog k="animations" /></Row></Group>
      <div className="bg-surface border border-border rounded-ui px-4 py-3.5 flex gap-3.5 items-center flex-wrap"><span className="font-semibold">Preview toast</span><span className="text-muted text-[12.5px]">Fires a sample notification using the position, style and duration above.</span><span className="flex-1" /><Button variant="outline" tone="success" onClick={() => toast('Customer CUS-1042 saved successfully', 'ok', 'Saved')}>Success</Button><Button variant="outline" tone="warn" onClick={() => toast('Credit limit exceeded by AED 12,400', 'warn')}>Warning</Button><Button variant="outline" tone="danger" onClick={() => toast('Posting failed: period 2026-P08 is locked', 'err')}>Error</Button></div>
    </section>
  );
}
