"use client";
import React,{useEffect,useState} from 'react';
import {Button,Card,Input,LocalizedText,Select,Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@pepbits/ops-ui';
import {useERP} from './erp-context';
import {useProduct,useProductPreferenceRequest} from './product-context';
import {authedFetch,readToken,type SentinelEvent} from '@pepbits/auth';
type Incident={id:string;status:string;revision:number;firstSeen:string;lastSeen:string;occurrences:number;diagnostic:Omit<SentinelEvent,'id'>};
export function ErrorMonitor(){
 const product=useProduct(),request=useProductPreferenceRequest()??authedFetch,token=readToken();const {t}=useERP();
 const [reference,setReference]=useState('');
 const [status,setStatus]=useState(''),[pageId,setPage]=useState(''),[offset,setOffset]=useState(0),[attempt,retry]=useState(0),[items,setItems]=useState<Incident[]>([]),[next,setNext]=useState<number|null>(null),[selected,setSelected]=useState<Incident>(),[history,setHistory]=useState<Array<{actor:string;status:string;at:string}>>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
 const headers={'X-Product-Id':product.id,'Content-Type':'application/json'};
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setItems([]);setSelected(undefined);
  request(`/monitoring/incidents?status=${encodeURIComponent(status)}&pageId=${encodeURIComponent(pageId)}&offset=${offset}&reference=${encodeURIComponent(reference)}`,{headers,signal:controller.signal}).then(async response=>{if(!response.ok)throw Error(response.status===403?'Monitoring administrator permission is required.':'Could not load monitoring incidents.');const body=await response.json();if(!controller.signal.aborted&&readToken()===token){setItems(body.incidents);setNext(body.nextOffset);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message==='Monitoring administrator permission is required.'?e.message:'Could not load monitoring incidents.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
 },[request,product.id,token,status,pageId,offset,attempt,reference]);
 async function detail(id:string){setError('');setBusy(true);try{const response=await request(`/monitoring/incidents/${encodeURIComponent(id)}`,{headers});if(!response.ok)throw Error();const body=await response.json();if(readToken()===token){setSelected(body.incident);setHistory(body.history);}}catch{setError('Could not load monitoring incidents.');}finally{setBusy(false);}}
 async function update(status:string){if(!selected)return;setBusy(true);setError('');try{const response=await request(`/monitoring/incidents/${selected.id}`,{method:'PATCH',headers,body:JSON.stringify({status,revision:selected.revision})});if(response.status===409){setError('Monitoring incident changed. Reload before saving.');return;}if(!response.ok)throw Error();await detail(selected.id);retry(n=>n+1);}catch{setError('Could not update monitoring incident.');}finally{setBusy(false);}}
 return <Card className="space-y-4 p-5" data-error-monitor>
  <h1 className="text-xl font-bold"><LocalizedText message="Error Monitor" /></h1>
  <p className="text-sm"><LocalizedText message="Sanitized application diagnostics collected by Sentinel." /></p>
  <div className="flex flex-wrap gap-3"><Input aria-label="Incident reference" placeholder="Incident reference" value={reference} onChange={e=>{setReference(e.target.value);setOffset(0);}} /><Select aria-label="Status" value={status} options={['','new','investigating','resolved'].map(value=>({value,label:value?t(`sentinel.status.${value}`):t('All')}))} onChange={e=>{setStatus(e.target.value);setOffset(0);}} /><Select aria-label="Page" value={pageId} options={[{value:'',label:t('All')},...Object.values(product.pages).map(p=>({value:p.id,label:t(p.titleKey??p.title)}))]} onChange={e=>{setPage(e.target.value);setOffset(0);}} /><Button onClick={()=>retry(n=>n+1)}><LocalizedText message="Refresh" /></Button></div>
  {error?<p role="alert">{t(error)}</p>:null}{loading?<p role="status"><LocalizedText message="Loading…" /></p>:null}
  {!loading&&!error&&!items.length?<p><LocalizedText message="No incidents found." /></p>:null}
  <Table className="w-full" density="comfortable"><TableHeader><TableRow>{['Page','Error','Status','Occurrences','Last seen','Actions'].map(title=><TableHead key={title}>{t(title)}</TableHead>)}</TableRow></TableHeader><TableBody>{items.map(item=><TableRow key={item.id}><TableCell>{t(product.pages[item.diagnostic.pageId]?.titleKey??product.pages[item.diagnostic.pageId]?.title??item.diagnostic.pageId)}</TableCell><TableCell>{t(`sentinel.code.${item.diagnostic.code}`)}</TableCell><TableCell>{t(`sentinel.status.${item.status}`)}</TableCell><TableCell>{item.occurrences}</TableCell><TableCell><bdi>{item.lastSeen}</bdi></TableCell><TableCell><Button disabled={busy} onClick={()=>void detail(item.id)}><LocalizedText message="View details" /></Button></TableCell></TableRow>)}</TableBody></Table>
  <div className="flex gap-2"><Button disabled={offset===0} onClick={()=>setOffset(n=>Math.max(0,n-50))}><LocalizedText message="Previous" /></Button><Button disabled={next===null} onClick={()=>setOffset(next!)}><LocalizedText message="Next" /></Button></div>
  {selected?<section className="space-y-3 rounded-lg border border-[var(--border)] p-4"><h2 className="font-bold"><LocalizedText message="Incident details" /></h2><p><bdi>{selected.id}</bdi></p><p><bdi>{selected.diagnostic.release} · {selected.diagnostic.platform}</bdi></p><p>{t(`sentinel.code.${selected.diagnostic.code}`)} · {selected.diagnostic.status??'—'} · {selected.diagnostic.line??'—'}:{selected.diagnostic.column??'—'}</p><p className="text-sm">{selected.diagnostic.breadcrumbs.map(id=>t(product.pages[id]?.titleKey??product.pages[id]?.title??id)).join(' → ')}</p><div className="flex gap-2">{['new','investigating','resolved'].map(status=><Button key={status} disabled={busy||selected.status===status} onClick={()=>void update(status)}>{t(`sentinel.status.${status}`)}</Button>)}</div><h3 className="font-semibold"><LocalizedText message="History" /></h3>{history.map((entry,i)=><p key={i} className="text-sm">{entry.actor} · {t(`sentinel.status.${entry.status}`)} · <bdi>{entry.at}</bdi></p>)}</section>:null}
 </Card>;
}
