import { ERP } from '@/lib/mock';
export interface LibBlock { title: string; sub?: string; text?: string; rows?: { k: string; v: string }[]; code?: string }
export interface LibSection { title: string; intro: string; showControls?: boolean; blocks: LibBlock[] }
const kv = (a: (readonly [string, string] | string[])[]) => a.map(x => ({ k: x[0], v: x[1] }));
export const LIBRARY: Record<string, LibSection> = {
      overview: { title: 'Architecture', intro: 'Vantage ERP is a schema-driven, preference-driven shell. Every page is generated from an entity schema by one of five shared page patterns; every visual decision is a token resolved at runtime from My preferences. Nothing on a page is styled or laid out locally.', blocks: [
        { title: 'Layers', sub: 'bottom to top', rows: kv([['tokens', 'CSS variables set on :root by the preferences engine: colors (theme), fonts, sizes, radius, density, sidebar side, toast anchor.'], ['components', '42 shared components (Button, Input, Select, MultiSelect, DatePicker, Toggle, Table, CardGrid, Pager, Tabs, Wizard, Rail, Modal, SidePanel, RecordCard, Toast, Sidebar, Header, TabStrip, CommandPalette, HelpPanel…). They only read tokens.'], ['schemas', 'One EntitySchema per record type: fields (type, options, required, basic/advanced filter, column) grouped in sections, plus quick actions. 30 entities ship in the mock.'], ['patterns', 'Dashboard, Worklist, RecordForm, Transaction (billing), ReportCenter, SheetUtility. A pattern takes a schema and renders the whole page.'], ['modules', 'Sales & Billing, Finance, HR & Payroll, Supply Chain, Library. A module is a menu tree (section → group → page) whose leaves point to a pattern + schema.']]) },
        { title: 'Why this matters', sub: 'single source of truth', text: 'Remove a field from the Customer schema and it disappears from the table, card grid, quick view, rail/tabs/wizard form, CSV export, advanced filters and column chooser at once. Change the Input component and every text field in every module changes. Add a theme and every component, including the sidebar, header and toasts, adopts it with no per-page work.' },
        { title: 'Runtime flow', sub: 'request → screen', code: 'Module select ─▶ menu tree loads into Sidebar\n   │\n   ▼\nLeaf route {page, entity} ─▶ Pattern picks Schema\n   │\n   ├─ Worklist: search + basic filters + advanced (collapsed) → rows → Table | CardGrid (pref)\n   │      row click → QuickView: RecordCard | Modal | SidePanel L/R (pref)\n   │      View/Edit/New → new TabStrip tab → RecordForm: Rail | Tabs | Wizard (pref)\n   │\n   └─ Save → Toast at pref position/duration → tab closes' } ] },
      prefs: { title: 'Preferences engine', intro: 'Preferences are a single JSON document persisted per user (localStorage in this prototype; a user_preferences table in production). Every consumer reads it through one hook; nothing stores a private copy.', blocks: [
        { title: 'Keys', sub: 'all keys in the document', rows: kv([['theme', 'light · dark · contrast · midnight · forest · sand · slate · solarized'], ['font, fs, fsForm, fsResult', 'Font family and three independent sizes (shell, form fields, results)'], ['density, corners', 'compact | comfortable; radius 0–12px'], ['sidebar, pinned', 'left | right; pinned open or hover-expand'], ['formLayout', 'rail | tabs | wizard — the one form schema renders in whichever the user picks'], ['resultView', 'table | cards'], ['quickView', 'card | modal | panel-left | panel-right'], ['pageSize', '10 · 20 · 50 · 100'], ['toastPos, toastDur, toastStyle', 'six anchors, 1–12 s, solid | light'], ['lang', 'en · ar (RTL) · hi · es · zh'], ['help, docs, docsPos', 'help assistant on/off; documentation panel on/off, top | bottom'], ['columns[entity]', 'Visible column order per worklist, saved when the user edits the column chooser']]) },
        { title: 'Contract', sub: 'how a component consumes preferences', code: '// hooks/usePreferences.ts\nexport function usePreferences(): [Preferences, (patch: Partial<Preferences>) => void]\n\n// components/RecordForm.tsx\nconst [{ formLayout }] = usePreferences();\nconst Layout = { rail: RailLayout, tabs: TabsLayout, wizard: WizardLayout }[formLayout];\nreturn <Layout sections={schema.sections} value={record} onChange={setRecord} readOnly={mode === "view"} />;' } ] },
      themes: { title: 'Theming', intro: 'A theme is 15 color tokens. Components never use literal colors; they use var(--accent), var(--surface) and friends, so a new theme is a data entry, not a code change. Contrast is validated per theme (text on surface ≥ 4.5:1, accent-fg on accent ≥ 4.5:1).', blocks: [
        { title: 'Tokens', sub: 'per theme', rows: kv([['bg / surface / surface2', 'Page canvas, cards and panels, subtle fills (table headers, hover)'], ['border', 'All hairlines'], ['text / muted', 'Primary and secondary text'], ['accent / accent-fg', 'Primary action, focus ring, active nav, and the text on top of it'], ['success / warn / danger', 'Status color, toast kinds, validation'], ['field', 'Input background (may differ from surface in dark themes)'], ['sidebar / sidebar-text', 'Navigation rail colors'], ['shadow', 'Elevation for popovers, panels, toasts']]) },
        { title: 'Adding a theme', sub: 'one object', code: 'export const themes: Record<ThemeId, ThemeTokens> = {\n  ...,\n  ocean: { name: "Ocean", bg: "#eef6f9", surface: "#ffffff", surface2: "#e2eef3", border: "#c7dbe3",\n           text: "#0e2a35", muted: "#4f6d7a", accent: "#0f6e8c", accentFg: "#ffffff", danger: "#b3261e",\n           success: "#1f7a4d", warn: "#9a5b00", field: "#ffffff", sidebar: "#0b2b38", sidebarText: "#cfe3ea",\n           shadow: "0 8px 24px rgba(14,42,53,.14)" }\n};\n// applyTheme(themes[prefs.theme]) writes each token to document.documentElement.style' } ] },
      i18n: { title: 'Localization', intro: 'All shell strings, actions and messages come from a dictionary keyed by language. Field labels in the mock are English; in production they resolve through the same dictionary with the schema key as fallback. Arabic flips direction: the sidebar, popovers and text alignment use logical properties (inset-inline-start, margin-inline-end) so RTL needs no extra CSS.', blocks: [
        { title: 'Languages shipped', sub: 'switch in My preferences', rows: kv([['en', 'English (fallback)'], ['ar', 'العربية — RTL'], ['hi', 'हिन्दी'], ['es', 'Español'], ['zh', '中文']]) },
        { title: 'Usage', sub: 'next-intl or a thin custom hook', code: 'const t = useT();            // t("advanced") → "Advanced filters" | "فلاتر متقدمة"\n<Button>{t("save")}</Button>\n// numbers & dates: Intl.NumberFormat / Intl.DateTimeFormat with prefs.lang' } ] },
      controls: { title: 'Buttons & inputs', intro: 'Form controls share one height scale (30px toolbar, 32px form), one border, one focus ring (2px accent-soft) and read font-size from --fs-form. Numeric and code values render in the mono face and align right.', showControls: true, blocks: [
        { title: 'Components', sub: 'props summary', rows: kv([['Button', 'variant: primary | secondary | outline | ghost · tone: accent | success | danger · size: sm | md · shortcut?: string (renders a kbd hint)'], ['Input', 'type: text | number | date | email | phone · readOnly · required · error?: string · mono'], ['Textarea', 'rows · spans full grid width by default'], ['Toggle', 'checked · onChange · labels: ["Yes","No"]'], ['FieldLabel', 'label · required marker · hint tooltip'], ['StatusPill', 'Colors itself from the status vocabulary (paid/approved → success, pending/draft → warn, overdue/blocked → danger)']]) } ] },
      selects: { title: 'Selects & pickers', intro: 'Select, MultiSelect and DatePicker share the input chrome. MultiSelect renders chosen values as chips inside the control and a checkbox list in a popover; it is the same component in advanced filters, forms and preferences.', showControls: true, blocks: [
        { title: 'Components', sub: 'props summary', rows: kv([['Select', 'options: {value,label}[] · placeholder · searchable (≥ 8 options) · readOnly'], ['MultiSelect', 'value: string[] · options · max? · chips inline, checkbox popover'], ['DatePicker / DateRange', 'ISO strings in and out; range used by advanced filters and reports'], ['ComboBox', 'Async lookup for foreign keys (customer on an invoice); shows code + name'], ['ColumnChooser', 'Popover of checkboxes + reorder; persists to prefs.columns[entity]']]) } ] },
      feedback: { title: 'Feedback: toasts, modals, panels', intro: 'Toasts stack at the preferred anchor with a progress bar for the preferred duration. Modal, SidePanel and RecordCard are one surface component with three placements; QuickView picks the placement from preferences.', blocks: [
        { title: 'Components', sub: 'props summary', rows: kv([['Toast', 'kind: ok | warn | err | info · title · message · duration (from prefs) · position (from prefs)'], ['Surface', 'placement: card | modal | panel-left | panel-right · header, body, footer slots · Esc and backdrop close'], ['QuickView', 'Schema-driven: first 8 non-textarea fields + quickActions from the schema'], ['ConfirmDialog', 'Destructive actions (sign out, void, delete)'], ['CommandPalette', 'Ctrl/⌘+K · searches every leaf of every module · ↑↓ ↵'], ['HelpPanel', 'Guided tour (spotlight + autoplay), page docs, shortcuts · F1']]) } ] },
      worklist: { title: 'Worklist pattern', intro: 'Every list page is the same component. It receives an EntitySchema and derives search, basic filters (fields flagged basic), advanced filters (fields flagged adv: selects, date ranges, minimum amounts, text contains), sortable columns, table or card rendering, pagination, column chooser, CSV export and the New / View / Edit actions.', blocks: [
        { title: 'Behaviour', sub: 'what is guaranteed on every worklist', rows: kv([['Search', 'Matches any visible column; / focuses it'], ['Advanced filters', 'Collapsed by default; badge shows active count; Clear resets everything'], ['Result view', 'Table or card grid from preferences; toggle on page also updates the preference'], ['Row click', 'Quick view with limited data and schema-defined actions'], ['View / Edit / New', 'Open a workspace tab; the header shows the tab title, so pages carry no title of their own'], ['Pagination', '10 · 20 · 50 · 100 rows; page numbers window ±2'], ['Columns', 'Choose and reorder; persisted per entity'], ['Export', 'CSV of the filtered result with formatted values']]) },
        { title: 'Usage', sub: 'one line per page', code: '// app/(shell)/[module]/[entity]/page.tsx\nexport default function Page({ params }) {\n  return <Worklist schema={schemas[params.entity]} />;\n}' } ] },
      forms: { title: 'Form layouts: rail, tabs, wizard', intro: 'RecordForm renders schema sections through one of three layout shells. Fields, validation, dirty tracking and save are identical; only navigation between sections differs. The user chooses the shell in My preferences and it applies to every record type in every module.', blocks: [
        { title: 'Shells', sub: 'same fields, different navigation', rows: kv([['Rail', 'Sticky left list of sections; all sections stacked; clicking scrolls'], ['Tabs', 'One section at a time; tab bar with field counts'], ['Wizard', 'Stepper with completed ticks; Back / Next; Save only on the last step']]) },
        { title: 'Field types', sub: 'FieldSchema.type', rows: kv([['text · code · email · phone', 'Input; code and numeric use the mono face'], ['number · currency · percent', 'Right-aligned numeric input; formatted in results'], ['date', 'DatePicker'], ['select · multiselect', 'Select / MultiSelect'], ['toggle', 'Toggle'], ['textarea', 'Full-width Textarea']]) } ] },
      shell: { title: 'Navigation shell', intro: 'The shell is Header + Sidebar + TabStrip + Footer. The sidebar is collapsed (56px) by default, expands to 260px on hover and collapses on mouse-out; a pin keeps it open. It can sit left or right. The header order is fixed: module, page title, notifications, branch, role, user name, profile.', blocks: [
        { title: 'Sidebar tree', sub: 'three levels', rows: kv([['Section', 'Masters · Transactions · Reports · Configuration (uppercase label, not clickable)'], ['Group', 'Icon tile + label + caret; collapsed rail shows only the tiles; clicking a tile while collapsed opens the group\'s first page'], ['Page', 'Leaf; active page gets the accent dot and the group gets an accent bar']]) },
        { title: 'Header', sub: 'left to right', rows: kv([['Module dropdown', 'Switching resets the sidebar tree and the workspace tab to that module\'s dashboard'], ['Page title', 'Title and crumb of the active tab; pages never render their own title'], ['Notifications', 'Badge + list popover'], ['Branch', 'Branches the user can access'], ['Role', 'Roles assigned to the user; acting role shown in the footer'], ['User name', 'Name and job title'], ['Profile', 'Settings · My profile · My preferences · Sign out']]) } ] },
      nextjs: { title: 'Next.js project structure', intro: 'Production stack: Next.js 15 (App Router, React Server Components for data, client components for the shell), TypeScript strict, Tailwind CSS 4 with the token layer exposed as CSS variables, Zustand for preferences and workspace tabs, TanStack Table/Query for lists, react-hook-form + zod for forms, next-intl for i18n. Only the data layer is mocked.', blocks: [
        { title: 'Folder layout', sub: 'apps/web', code: 'app/\n  layout.tsx                 # ThemeProvider · PreferencesProvider · IntlProvider\n  (shell)/\n    layout.tsx               # Header · Sidebar · TabStrip · Footer · HelpPanel · Toaster\n    [module]/page.tsx        # Dashboard (pattern) — module from route\n    [module]/[entity]/page.tsx           # Worklist\n    [module]/[entity]/[id]/page.tsx      # RecordForm (view/edit) · /new\n    [module]/billing/page.tsx            # Transaction pattern\n    [module]/reports/page.tsx            # ReportCenter\n    [module]/excel/page.tsx              # SheetUtility\n    preferences/page.tsx · settings/page.tsx · profile/page.tsx\n    library/[section]/page.tsx\ncomponents/\n  primitives/    Button Input Select MultiSelect DatePicker Toggle Textarea Kbd StatusPill\n  surfaces/      Surface Modal SidePanel RecordCard Toast ConfirmDialog\n  navigation/    Header Sidebar NavTree TabStrip Footer CommandPalette\n  data/          DataTable CardGrid Pager ColumnChooser FilterBar AdvancedFilters\n  forms/         RecordForm RailLayout TabsLayout WizardLayout FieldRenderer\n  patterns/      Dashboard Worklist Transaction ReportCenter SheetUtility\n  help/          HelpPanel GuidedTour Spotlight DocsPanel\nlib/\n  schemas/       customer.ts product.ts … (EntitySchema each) · index.ts registry\n  modules/       sales.ts finance.ts hr.ts scm.ts library.ts (menu trees)\n  themes/        tokens.ts themes.ts applyTheme.ts\n  i18n/          en.json ar.json hi.json es.json zh.json\n  prefs/         schema.ts (zod) store.ts (zustand + persist) usePreferences.ts\n  sheet/         evaluate.ts csv.ts\n  mock/          generator.ts (seeded) api.ts (MSW handlers)\nstyles/globals.css              # @theme tokens → CSS variables' },
        { title: 'Key decisions', sub: 'and why', rows: kv([['Tokens as CSS variables', 'Runtime theme switching without rebuilding Tailwind; Tailwind utilities reference var(--accent) via @theme'], ['Workspace tabs in a client store', 'View/Edit/New open tabs; URL reflects the active tab so deep links work'], ['Schema registry', 'Pages are one line; adding an entity = one schema file + one menu leaf'], ['MSW mocks', 'Same fetch calls as production; swap the handler for the real API'], ['RTL via logical properties', 'dir="rtl" on <html>; no mirrored stylesheets'], ['Keyboard map', 'One useHotkeys registry; every shortcut is listed in HelpPanel and the ? dialog']]) } ] },
      types: { title: 'TypeScript contracts', intro: 'The three types that drive the whole application.', blocks: [
        { title: 'lib/schemas/types.ts', sub: 'entity schema', code: 'export type FieldType = "text" | "code" | "email" | "phone" | "number" | "currency" | "percent" | "date" | "select" | "multiselect" | "toggle" | "textarea";\n\nexport interface FieldSchema {\n  key: string; label: string; type: FieldType;\n  options?: readonly string[]; required?: boolean;\n  column?: boolean;      // default visible column in worklists\n  basicFilter?: boolean; // shown beside search\n  advFilter?: boolean;   // shown in the collapsed Advanced panel\n  prefix?: string; min?: number; max?: number;\n}\nexport interface SectionSchema { title: string; fields: FieldSchema[] }\nexport interface QuickAction { label: string; act: "view" | "edit" | "nav" | "command"; page?: string; command?: string }\nexport interface EntitySchema {\n  id: string; label: string; plural: string; module: ModuleId;\n  titleKey: string; sections: SectionSchema[]; quickActions: QuickAction[];\n}' },
        { title: 'lib/prefs/schema.ts', sub: 'preferences (zod)', code: 'export const Preferences = z.object({\n  theme: z.enum(["light","dark","contrast","midnight","forest","sand","slate","solarized"]),\n  font: z.string(), fs: z.number().min(11).max(16), fsForm: z.number(), fsResult: z.number(),\n  density: z.enum(["compact","comfortable"]), corners: z.number().min(0).max(12),\n  sidebar: z.enum(["left","right"]), pinned: z.boolean(),\n  formLayout: z.enum(["rail","tabs","wizard"]), resultView: z.enum(["table","cards"]),\n  quickView: z.enum(["card","modal","panel-left","panel-right"]),\n  pageSize: z.union([z.literal(10), z.literal(20), z.literal(50), z.literal(100)]),\n  toastPos: z.enum(["top-left","top-center","top-right","bottom-left","bottom-center","bottom-right"]),\n  toastDur: z.number().min(1).max(12), toastStyle: z.enum(["solid","light"]),\n  lang: z.enum(["en","ar","hi","es","zh"]), help: z.boolean(), docs: z.boolean(), docsPos: z.enum(["top","bottom"]),\n  animations: z.boolean(), columns: z.record(z.array(z.string()))\n});\nexport type Preferences = z.infer<typeof Preferences>;' },
        { title: 'lib/modules/types.ts', sub: 'menu tree', code: 'export type Route = { page: "dashboard" | "worklist" | "form" | "billing" | "reports" | "excel" | "prefs" | "settings" | "profile" | "library"; entity?: string; id?: string; mode?: "view" | "edit" | "new"; section?: string };\nexport interface MenuLeaf { label: string; route: Route }\nexport interface MenuGroup { id: string; label: string; icon: string; children: MenuLeaf[] }\nexport interface MenuSection { title: "masters" | "transactions" | "reports" | "configuration" | string; items: MenuGroup[] }\nexport interface ModuleDef { id: ModuleId; name: string; short: string; tagline: string; sections: MenuSection[] }' } ] },
      tailwind: { title: 'Tailwind & tokens', intro: 'Tailwind 4 reads design tokens from CSS variables, so utilities like bg-surface, text-muted and border-border resolve to whatever the active theme writes to :root. Components use utilities; themes and preferences change variables. No component ever hard-codes a color, radius or font size.', blocks: [
        { title: 'styles/globals.css', sub: '@theme mapping', code: '@import "tailwindcss";\n\n@theme {\n  --color-bg: var(--bg); --color-surface: var(--surface); --color-surface2: var(--surface2);\n  --color-border: var(--border); --color-text: var(--text); --color-muted: var(--muted);\n  --color-accent: var(--accent); --color-accent-fg: var(--accent-fg);\n  --color-danger: var(--danger); --color-success: var(--success); --color-warn: var(--warn);\n  --color-field: var(--field); --color-sidebar: var(--sidebar); --color-sidebar-text: var(--sidebar-text);\n  --font-sans: var(--font); --font-mono: var(--mono);\n  --radius-ui: var(--radius); --text-ui: var(--fs); --text-form: var(--fs-form); --text-result: var(--fs-result);\n}\n\n/* defaults = Light theme; applyTheme() overrides at runtime */\n:root { --bg:#f6f7f8; --surface:#fff; --accent:#1f6f8b; --radius:0px; --fs:13px; ... }' },
        { title: 'Component example', sub: 'components/primitives/Button.tsx', code: 'export function Button({ variant = "secondary", tone = "accent", shortcut, className, ...props }: ButtonProps) {\n  return (\n    <button\n      className={cn(\n        "h-[30px] px-3 text-ui rounded-ui border inline-flex items-center gap-2 whitespace-nowrap",\n        variant === "primary" && "bg-accent text-accent-fg border-accent font-semibold hover:brightness-110",\n        variant === "secondary" && "bg-surface text-text border-border hover:border-accent",\n        variant === "outline" && tone === "danger" && "bg-transparent text-danger border-danger",\n        className)}\n      {...props}>\n      {props.children}{shortcut && <Kbd>{shortcut}</Kbd>}\n    </button>\n  );\n}' } ] },
      keys: { title: 'Keyboard shortcuts', intro: 'One registry (lib/hotkeys.ts) declares every shortcut with scope (global, worklist, form, sheet). The same registry renders the ? dialog and the Help panel list, so documentation cannot drift from behaviour.', blocks: [
        { title: 'Global', sub: 'available everywhere', rows: kv(ERP.shortcuts) },
        { title: 'Sheet utility', sub: 'inside the grid', rows: kv([['↑ ↓ ← →', 'Move selection'], ['Enter', 'Commit and move down'], ['Tab', 'Commit and move right'], ['Ctrl + D', 'Fill down from the selected cell (formula references shift)'], ['Delete', 'Clear cell']]) } ] }
    };
export const LIBRARY_NAV: [string, string][] = [['overview', 'Architecture'], ['prefs', 'Preferences'], ['themes', 'Theming'], ['i18n', 'Localization'], ['controls', 'Controls'], ['selects', 'Selects'], ['feedback', 'Feedback'], ['worklist', 'Worklist'], ['forms', 'Forms'], ['shell', 'Shell'], ['nextjs', 'Next.js'], ['types', 'Types'], ['tailwind', 'Tailwind'], ['keys', 'Shortcuts']];
