"use client";
import React,{useState} from 'react';
import {Layers,Code2,LayoutTemplate,BookOpen} from 'lucide-react';
import {Card,CardHeader,CardTitle,CardContent,CardGrid,Button,Badge,SearchInput,Select,Tabs,Textarea,EmptyState,DescriptionList,useLocalization} from '@pepbits/ops-ui';
import {PAGE_TEMPLATES,TEMPLATE_BY_ID,TEMPLATE_GROUPS,type PageDefinition,type TemplateLayout} from '@pepbits/erp-config';
import {useERP,useProduct} from '@pepbits/erp-shell';
import {useNavigation} from '@pepbits/platform-ports';
import {TemplateDemo,type TemplateDemoProps} from './template-demo';
import {PreferenceControl} from '../preferences/policy-controls';
import demoSource from './template-example.generated.json';

export function TemplateLibraryPage({page}: {page:PageDefinition}) {
 const {t}=useLocalization(),{preferences,preferencePolicy,preferencesAvailable,updatePreference}=useERP(),product=useProduct(),navigation=useNavigation();
 const [query,setQuery]=useState(''),[group,setGroup]=useState('all'),[tab,setTab]=useState('preview'),[scenario,setScenario]=useState<TemplateDemoProps['scenario']>('ready'),[revision,setRevision]=useState(0),[copied,setCopied]=useState<'idle'|'yes'|'failed'>('idle');
 const selected=TEMPLATE_BY_ID[page.id];
 const entries=PAGE_TEMPLATES.filter(item=>product.pages[item.id]&&(group==='all'||item.group===group)&&`${t(item.title)} ${item.id} ${item.tags.join(' ')} ${item.engine}`.toLowerCase().includes(query.toLowerCase()));
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setCopied('yes');}catch{setCopied('failed');}};
 const code=selected?`${demoSource.source}\nimport { useERP } from '@pepbits/erp-shell';\n// Selected configuration. Render this inside your application's providers.\nexport const definition = ${JSON.stringify(selected,null,2)} satisfies PageTemplateDefinition;\n\nexport default function ExamplePage() { const { preferences, preferencePolicy, preferencesAvailable, updatePreference } = useERP(); return <TemplateDemo definition={definition} preferences={preferences} preferencePolicy={preferencePolicy} preferencesAvailable={preferencesAvailable} onPreferenceChange={updatePreference}/>; }\n`:'';
 return <div className="space-y-4" data-template-library={page.id}>
  {!selected?.designFamily?<Card><CardContent className="flex flex-wrap items-center justify-between gap-4"><div className="max-w-4xl space-y-2"><div className="flex items-center gap-2"><LayoutTemplate className="size-5 text-[var(--primary)]"/><Badge tone="brand">{t('template.library')}</Badge><Badge>{t('template.templateCount',{count:PAGE_TEMPLATES.length})}</Badge></div><h2 className="text-2xl font-bold">{t(selected?selected.title:'template.choose')}</h2><p className="text-sm text-[var(--text-muted)]">{t('template.libraryHelp')}</p></div>{selected?<Button onClick={()=>navigation.open({pageId:'page-templates'})}>{t('template.backLibrary')}</Button>:null}</CardContent></Card>:null}
  {!selected?<>
   <Card><CardContent className="flex flex-wrap items-end gap-3"><SearchInput aria-label="template.searchTemplates" placeholder="template.searchTemplates" className="min-w-64 flex-1" value={query} onChange={setQuery} onClear={()=>setQuery('')}/><Select label="template.groupLabel" value={group} onChange={event=>setGroup(event.target.value)} options={[{value:'all',label:'template.all'},...TEMPLATE_GROUPS.map(item=>({value:item.id,label:item.title}))]}/></CardContent></Card>
   <p role="status" className="text-sm text-[var(--text-muted)]">{t('template.matchCount',{count:entries.length})}</p>
   {!entries.length?<EmptyState/>:<CardGrid columns={3}>{entries.map(item=><Card key={item.id} as="article" className="flex flex-col"><CardContent className="flex h-full flex-col gap-3"><div className="flex items-center justify-between"><Layers className="size-6 text-[var(--primary)]"/><Badge>{t(`template.group.${item.group}`)}</Badge></div><h3 className="text-lg font-bold">{t(item.title)}</h3><p className="flex-1 text-sm text-[var(--text-muted)]">{t(item.description)}</p><div className="flex flex-wrap gap-1">{item.tags.map(tag=><Badge key={tag}>{tag}</Badge>)}</div><Button variant="primary" onClick={()=>navigation.open({pageId:item.id})}>{t('template.explore')}</Button></CardContent></Card>)}</CardGrid>}
  </>:<>
   <Card><CardContent className="flex flex-wrap items-end justify-between gap-3"><Tabs items={[{id:'preview',label:'template.preview',icon:<LayoutTemplate className="size-4"/>},{id:'code',label:'template.typescript',icon:<Code2 className="size-4"/>},{id:'configuration',label:'template.configuration'},{id:'guide',label:'template.guide',icon:<BookOpen className="size-4"/>}]} value={tab} onChange={value=>{setTab(value);setCopied('idle');}}/>
    <div className="flex flex-wrap items-end gap-2">{!selected.designFamily&&['master','order','finance','case','result','entity'].includes(selected.engine)?<PreferenceControl preferenceKey="formNavigation"><Select label="template.layout" value={preferences.formNavigation} onChange={event=>updatePreference('formNavigation',event.target.value as TemplateLayout)} options={['rail','tabs','wizard'].map(value=>({value,label:`template.layout.${value}`}))}/></PreferenceControl>:null}<Select label="template.scenario" value={scenario} onChange={event=>setScenario(event.target.value as TemplateDemoProps['scenario'])} options={['ready','loading','empty','denied','readOnly','failure'].map(value=>({value,label:`template.scenario.${value}`}))}/><Button onClick={()=>{setRevision(value=>value+1);setScenario('ready');}}>{t('template.reset')}</Button></div>
   </CardContent></Card>
   <div hidden={tab!=='preview'} className="space-y-3"><p className="text-sm text-[var(--text-muted)]">{t('template.localDemo')}</p><TemplateDemo key={`${selected.id}:${revision}`} definition={selected} preferences={preferences} preferencePolicy={preferencePolicy} preferencesAvailable={preferencesAvailable} onPreferenceChange={updatePreference} scenario={scenario}/></div>
   {tab==='preview'?null:tab==='code'||tab==='configuration'?<Card><CardHeader><CardTitle title={tab==='code'?'template.typescript':'template.configuration'} action={<Button onClick={()=>void copy(tab==='code'?code:JSON.stringify(selected,null,2))}>{t('catalog.copy')}</Button>}/></CardHeader><CardContent className="space-y-3"><p>{t('template.codeHelp')}</p><Textarea label="template.source" aria-label="template.source" value={tab==='code'?code:JSON.stringify(selected,null,2)} readOnly dir="ltr" rows={26} spellCheck={false} className="font-mono text-xs" onFocus={event=>event.target.select()}/><p role="status">{t(copied==='yes'?'catalog.copied':copied==='failed'?'catalog.copyFailed':'catalog.copyHint')}</p></CardContent></Card>:<Card><CardHeader><CardTitle title="template.guide"/></CardHeader><CardContent className="space-y-4"><DescriptionList layout="stacked" items={[{id:'purpose',label:'template.purpose',value:t(selected.description)},{id:'components',label:'template.components',value:t('template.componentHelp')},{id:'preferences',label:'template.preferences',value:t('template.preferenceHelp')},{id:'adapter',label:'template.integration',value:t('template.adapterHelp')},{id:'scope',label:'template.scope',value:t('template.scopeHelp')},{id:'limitations',label:'template.domainRules',value:t('template.domainHelp')}]}/></CardContent></Card>}
  </>}
 </div>;
}
