"use client";
import {usePreferenceChoice,type PreferenceHost} from "../preference-choice";
import React,{useState} from 'react';
import {Card,CardHeader,CardTitle,CardContent,CardGrid,Button,Input,Textarea,Select,Checkbox,Calendar,DateInput,SearchInput,EmptyState,DataValue,DescriptionList,Badge,StatCard,Tabs,Pagination,TableContainer,Table,TableHeader,TableBody,TableRow,TableHead,TableCell,Modal,useLocalization} from '@pepbits/ops-ui';
import type {PageTemplateDefinition,TemplateDocument,TemplateValue,Formatters,DataColumn,Density} from '@pepbits/erp-config';
import {TemplateSchedule,TemplateMatrix} from './template-specialized';
import {PreferencePreview} from '../preference-preview';
import {DataTable} from '../worklist/data-table';
import {TemplateFields,TemplateBoard,TemplateTimeline,TemplateChecklist} from './template-parts';
import {lineTotals} from './template-state';
export interface TemplateEngineProps extends PreferenceHost {definition:PageTemplateDefinition;document:TemplateDocument;update:(document:TemplateDocument)=>void;disabled:boolean;errors:Record<string,string>;format:Formatters;density:Density;precision:number;pageSize:10|20|50|100;resultView:'table'|'cards'}
export function TemplateLines({document,update,disabled,format,precision,density,financial=false,result=false}:Pick<TemplateEngineProps,'document'|'update'|'disabled'|'format'|'precision'|'density'>&{financial?:boolean;result?:boolean}) {
 const {t}=useLocalization();
 const change=(id:string,key:string,value:TemplateValue)=>update({...document,lines:document.lines.map(line=>line.id===id?{...line,[key]:value}:line)});
 const totals=lineTotals(document.lines,precision);
 return <Card><CardHeader><CardTitle title={result?'template.measurements':financial?'template.entries':'template.lineItems'} action={!result?<Button disabled={disabled} onClick={()=>update({...document,lines:[...document.lines,{id:crypto.randomUUID(),description:'',quantity:1,price:0,debit:0,credit:0,result:'',reference:'',checked:false}]})}>{t('template.addLine')}</Button>:undefined}/></CardHeader><CardContent className="space-y-3">
  <TableContainer><Table density={density==='compact'?'compact':'comfortable'} className="w-full min-w-[700px]" striped bordered><TableHeader><TableRow>{["description",...(result?["result","reference"]:financial?["debit","credit"]:["quantity","price"]),"actions"].map(key=><TableHead key={key} className="p-2 text-start">{t(`template.field.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{document.lines.map((line,index)=><TableRow key={line.id}>
   <TableCell className="p-2"><Input aria-label={t('template.lineLabel',{field:t('template.field.description'),index:index+1})} value={line.description} disabled={disabled} onChange={event=>change(line.id,'description',event.target.value)}/></TableCell>
   {(result?['result','reference']:financial?['debit','credit']:['quantity','price']).map(key=><TableCell key={key} className="p-2"><Input aria-label={t('template.lineLabel',{field:t(`template.field.${key}`),index:index+1})} type={result?'text':'number'} min={0} step={key==='quantity'?1:0.01} value={String(line[key as keyof typeof line])} disabled={disabled} onChange={event=>change(line.id,key,result?event.target.value:event.target.value===''?NaN:Number(event.target.value))}/></TableCell>)}
   <TableCell className="p-2"><Button variant="ghost" disabled={disabled} onClick={()=>update({...document,lines:document.lines.filter(item=>item.id!==line.id)})}>{t('template.remove')}</Button></TableCell>
  </TableRow>)}</TableBody></Table></TableContainer>
  {!document.lines.length?<EmptyState/>:null}
  {!result?<DescriptionList items={financial?[{id:'debit',label:'template.field.debit',value:format.money(totals.debit)},{id:'credit',label:'template.field.credit',value:format.money(totals.credit)},{id:'difference',label:'template.difference',value:<Badge tone={totals.difference===0?'success':'danger'}>{format.money(totals.difference)}</Badge>}]:[{id:'total',label:'template.total',value:<b className="text-xl">{format.money(totals.amount)}</b>}]}/>:null}
 </CardContent></Card>;
}
export function TemplateList(props:TemplateEngineProps) {
 const {definition,document,update,disabled,format,density}=props;const {t}=useLocalization();const split=definition.id==='template-split-list-detail';
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1),[preview,setPreview]=useState<Record<string,TemplateValue>|null>(null),[sort,setSort]=useState<{key:string;direction:'asc'|'desc'}|null>(null);
 const [pageSize,setPageSize,pageSizeLocked]=usePreferenceChoice(props,'pageSize');
 const columns:DataColumn[]=definition.columns.map(column=>({...column,label:t(column.label),sortable:true,editable:column.key==='name'}));
 const filtered=document.rows.filter(row=>(status==='all'||row.status===status)&&Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase())).sort((left,right)=>{if(!sort)return 0;const a=left[sort.key],b=right[sort.key];return (typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b)))*(sort.direction==='asc'?1:-1);});
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),current=Math.min(page,pages),rows=filtered.slice((current-1)*pageSize,current*pageSize);
 const move=(code:string,next:string)=>update({...document,rows:document.rows.map(row=>row.code===code?{...row,status:next}:row)});
 return <div className="space-y-3"><Card><CardContent className="flex flex-wrap items-end gap-3"><SearchInput aria-label="template.searchRecords" value={query} onChange={value=>{setQuery(value);setPage(1);}} onClear={()=>{setQuery('');setPage(1);}} className="min-w-64 flex-1"/><Select label="template.field.status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}} options={[{value:'all',label:'template.all'},...definition.stages.map(value=>({value,label:`template.status.${value}`}))]}/><Button disabled={disabled||!selected.length} onClick={()=>{update({...document,rows:document.rows.map(row=>selected.includes(String(row.code))?{...row,status:'completed'}:row)});setSelected([]);}}>{t('template.completeSelected',{count:selected.length})}</Button></CardContent></Card>
  <div className={split?'grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_300px]':'space-y-3'}><div className="min-w-0 space-y-3">{!filtered.length?<EmptyState/>:definition.view==='board'?<TemplateBoard rows={filtered} stages={definition.stages} onMove={move} disabled={disabled}/>:definition.view==='timeline'?<TemplateTimeline rows={filtered}/>:definition.view==='cards'||props.resultView==='cards'?<CardGrid columns={3} style={{'--fs-scale':'var(--fs-result)'} as React.CSSProperties}>{rows.map(row=><Card key={String(row.code)}><CardContent className="space-y-3"><b>{row.name}</b><DescriptionList items={definition.columns.map(column=>({id:column.key,label:column.label,value:column.type==='money'?format.money(Number(row[column.key])):column.key==='status'?t(`template.status.${row.status}`):String(row[column.key])}))}/><Button onClick={()=>setPreview(row)}>{t('template.open')}</Button></CardContent></Card>)}</CardGrid>:<Card><DataTable rows={rows.map(row=>({...row,status:t(`template.status.${row.status}`)}))} columns={columns} primaryKey="code" displayKey="name" selected={selected} onToggle={id=>setSelected(list=>list.includes(id)?list.filter(item=>item!==id):[...list,id])} onToggleAll={()=>setSelected(rows.every(row=>selected.includes(String(row.code)))?selected.filter(id=>!rows.some(row=>row.code===id)):[...new Set([...selected,...rows.map(row=>String(row.code))])])} sort={sort} onSort={column=>setSort({key:column.key,direction:sort?.key===column.key&&sort.direction==='asc'?'desc':'asc'})} onPreview={setPreview} onView={setPreview} onEdit={setPreview} canEdit={false} onCellCommit={!disabled?(row,column,value)=>update({...document,rows:document.rows.map(item=>item.code===row.code?{...item,[column.key]:value}:item)}):undefined} density={density} format={format} zebra={props.preferences.zebraStripes} stickyHeader={props.preferences.stickyTableHeader} wrap={props.preferences.wrapCellText}/></Card>}
  {definition.view!=='board'?<Pagination pageSizeDisabled={pageSizeLocked} page={current} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={size=>{setPageSize(size);setPage(1);}}/>:null}
  </div>{split?<Card><CardHeader><CardTitle title="template.recordDetails"/></CardHeader><CardContent>{preview?<DescriptionList items={definition.columns.map(column=>({id:column.key,label:column.label,value:String(preview[column.key])}))}/>:<EmptyState/>}</CardContent></Card>:null}</div>
  {!split?<PreferencePreview mode={props.preferences.previewMode} open={!!preview} onClose={()=>setPreview(null)} title="template.recordDetails"><DescriptionList items={preview?definition.columns.map(column=>({id:column.key,label:column.label,value:String(preview[column.key])})):[]}/></PreferencePreview>:null}
 </div>;
}
export function TemplateBooking(props:TemplateEngineProps) {
 const {definition,document,update,disabled,errors,format}=props;const {t}=useLocalization();
 const date=String(document.values.effectiveDate??'2026-09-09');
 return <div className="space-y-3"><CardGrid columns={3}><StatCard label="template.available" value={3}/><StatCard label="template.booked" value={document.rows.length}/><StatCard label="template.field.resource" value={String(document.values.resource)}/></CardGrid>
  <CardGrid className="gap-4 xl:grid-cols-[320px_minmax(0,1fr)]"><Card><CardContent className="space-y-4"><Calendar className="w-full max-w-full" label="template.field.effectiveDate" value={date} onChange={value=>update({...document,values:{...document.values,effectiveDate:value}})} disabled={disabled}/><Select label="template.field.resource" value={String(document.values.resource)} disabled={disabled} options={['Room A','Room B','Room C'].map(value=>({value,label:value}))} onChange={event=>update({...document,values:{...document.values,resource:event.target.value}})}/></CardContent></Card>
  <div className="space-y-3"><TemplateFields section={definition.sections[0]} values={document.values} errors={errors} disabled={disabled} onChange={(id,value)=>update({...document,values:{...document.values,[id]:value}})}/><Card><CardHeader><CardTitle title="template.availableSlots"/></CardHeader><CardContent className="flex flex-wrap gap-2">{['09:00','10:00','11:00','14:00','15:00'].map(time=><Button key={time} data-template-time={time} disabled={disabled||time==='11:00'} variant={document.values.startTime===time?'primary':'secondary'} aria-pressed={document.values.startTime===time} onClick={()=>update({...document,values:{...document.values,startTime:time,endTime:time.replace(':00',':30')}})}>{format.time(time)}{time==='11:00'?` · ${t('template.booked')}`:''}</Button>)}</CardContent></Card></div></CardGrid>
  {['timeline','board','matrix'].includes(definition.view)?<TemplateSchedule {...props}/>:null}
 </div>;
}
export function TemplateChart({rows,format}: {rows:TemplateDocument['rows'];format:Formatters}) {
 const {t}=useLocalization();const maximum=Math.max(1,...rows.map(row=>Number(row.amount)||0));
 return <Card><CardHeader><CardTitle title="template.comparison"/></CardHeader><CardContent><div role="list" aria-label={t('template.comparison')} className="space-y-3">{rows.map(row=><div role="listitem" key={String(row.code)} className="grid grid-cols-[100px_minmax(0,1fr)_100px] items-center gap-3 text-sm"><span>{row.name}</span><div aria-hidden className="h-6 rounded bg-[var(--surface-2)]"><div className="h-full rounded bg-[var(--primary)]" style={{width:`${Math.max(0,Number(row.amount)||0)/maximum*100}%`}}/></div><DataValue value={Number(row.amount)} format={format.number} numeric/></div>)}</div></CardContent></Card>;
}
export function TemplateReport(props:TemplateEngineProps) {
 const {definition,document,format}=props;const {t}=useLocalization();const [from,setFrom]=useState('2026-09-09'),[to,setTo]=useState('2026-09-30'),[range,setRange]=useState({from,to}),[error,setError]=useState(false);
 const rows=document.rows.filter(row=>String(row.date)>=range.from&&String(row.date)<=range.to);
 const total=rows.reduce((sum,row)=>sum+Number(row.amount),0);
 return <div className="space-y-3"><Card><CardContent className="flex flex-wrap items-end gap-3"><DateInput label="template.from" value={from} max={to} onChange={event=>setFrom(event.target.value)}/><DateInput label="template.to" value={to} min={from} onChange={event=>setTo(event.target.value)}/><Button variant="primary" onClick={()=>{setError(!from||!to||from>to);if(from&&to&&from<=to)setRange({from,to});}}>{t('template.runReport')}</Button>{error?<p role="alert">{t('template.validation.date')}</p>:null}</CardContent></Card>
  <CardGrid columns={3}><StatCard label="template.records" value={rows.length}/><StatCard label="template.total" value={format.money(total)}/><StatCard label="template.average" value={format.money(rows.length?total/rows.length:0)}/></CardGrid>
  {definition.view==='matrix'?<TemplateMatrix {...props} document={{...document,rows}}/>:null}
  {definition.engine==='dashboard'?<TemplateChart rows={rows} format={format}/>:null}
  {!rows.length?<EmptyState/>:<Card><CardHeader><CardTitle title={definition.title} subtitle="template.sampleOnly"/></CardHeader><CardContent><TableContainer><Table className="w-full" striped bordered><TableHeader><TableRow>{definition.columns.map(column=><TableHead key={column.key} className="p-3 text-start">{t(column.label)}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={String(row.code)}>{definition.columns.map(column=><TableCell key={column.key} className="p-3">{column.type==='money'?format.money(Number(row[column.key])):column.type==='date'?format.date(String(row[column.key])):column.key==='status'?t(`template.status.${row.status}`):String(row[column.key])}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>}
 </div>;
}
export function TemplateReconcile(props:TemplateEngineProps) {
 const {document,update,disabled,format}=props;const {t}=useLocalization();const [left,setLeft]=useState<string|null>(null),[right,setRight]=useState<string|null>(null);
 const matching=left&&right&&document.rows.find(row=>row.code===left)?.amount===document.rows.find(row=>row.code===right)?.amount;
 return <div className="space-y-3"><CardGrid columns={2}>{['ledger','statement'].map(side=><Card key={side}><CardHeader><CardTitle title={t(`template.${side}`)}/></CardHeader><CardContent className="space-y-2">{document.rows.filter(row=>row.status!=='completed').map(row=><Button key={String(row.code)} className="w-full justify-between" aria-pressed={(side==='ledger'?left:right)===row.code} onClick={()=>side==='ledger'?setLeft(String(row.code)):setRight(String(row.code))}><span>{row.code}</span><span>{format.money(Number(row.amount))}</span></Button>)}</CardContent></Card>)}</CardGrid><Button variant="primary" disabled={disabled||!matching} onClick={()=>{update({...document,rows:document.rows.map(row=>row.code===left||row.code===right?{...row,status:'completed'}:row)});setLeft(null);setRight(null);}}>{t('template.match')}</Button><p className="text-sm text-[var(--text-muted)]">{t('template.matchHelp')}</p></div>;
}
export function TemplateAdministration(props:TemplateEngineProps) {
 const {definition,document,update,disabled,errors,format}=props;const {t}=useLocalization();const [step,setStep]=useState('configure');
 return <div className="space-y-3"><Tabs items={['configure','review','history'].map(id=>({id,label:`template.${id}`}))} value={step} onChange={setStep}/>
  {step==='history'?<TemplateTimeline rows={document.rows}/>:step==='review'?<DescriptionList items={Object.entries(document.values).filter(([id])=>definition.sections.some(section=>section.fields.some(field=>field.id===id))).map(([id,value])=>({id,label:`template.field.${id}`,value:String(value)}))}/>:<>
   <TemplateFields section={definition.sections[0]} values={document.values} errors={errors} disabled={disabled} onChange={(id,value)=>update({...document,values:{...document.values,[id]:value}})}/>
   {definition.id==='template-permissions-matrix'||definition.id==='template-policy-editor'?<Card><CardContent><Table className="w-full" bordered><TableHeader><TableRow><TableHead className="p-3">{t('template.field.name')}</TableHead>{['view','edit','approve'].map(action=><TableHead className="p-3" key={action}>{t(`template.${action}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{['staff','manager','administrator'].map(role=><TableRow key={role}><TableCell className="p-3">{t(`template.${role}`)}</TableCell>{['view','edit','approve'].map(action=><TableCell className="p-3" key={action}><Checkbox aria-label={`${t(`template.${role}`)}: ${t(`template.${action}`)}`} disabled={disabled} checked={!!document.values[`${role}.${action}`]} onChange={event=>update({...document,values:{...document.values,[`${role}.${action}`]:event.target.checked}})}/></TableCell>)}</TableRow>)}</TableBody></Table></CardContent></Card>:<TemplateChecklist lines={document.lines} disabled={disabled} onChange={lines=>update({...document,lines})}/>}
  </>}
 </div>;
}
