"use client";
import React,{useState} from 'react';
import {Card,CardHeader,CardTitle,CardContent,CardGrid,Button,Badge,Input,Select,Textarea,FilePicker,EmptyState,TableContainer,Table,TableHeader,TableBody,TableRow,TableHead,TableCell,DescriptionList,useLocalization} from '@pepbits/ops-ui';
import {parseCsv} from '@pepbits/erp-data';
import type {TemplateEngineProps} from './template-engines';
export function TemplateSchedule({document,update,disabled,definition,format}:TemplateEngineProps) {
 const {t,language}=useLocalization();
 const resources=[...new Set(document.rows.map(row=>String(row.resource??'')).filter(Boolean))];
 if(definition.view==='board')return <CardGrid columns={3}>{resources.map((resource,index)=><Card key={resource}><CardHeader><CardTitle title={resource} action={<Badge tone={index===1?'warning':'success'}>{t(index===1?'template.booked':'template.available')}</Badge>}/></CardHeader><CardContent className="space-y-3"><p>{t('template.capacity',{count:2})}</p><Button disabled={disabled||index===1} onClick={()=>update({...document,values:{...document.values,resource}})}>{t('template.selectResource')}</Button></CardContent></Card>)}</CardGrid>;
 const times=definition.view==='matrix'?['Mon','Tue','Wed','Thu','Fri']:['09:00','10:00','11:00','14:00','15:00'];
 return <Card><CardHeader><CardTitle title="template.resourceSchedule"/></CardHeader><CardContent><TableContainer><Table className="w-full min-w-[680px]" bordered><TableHeader><TableRow><TableHead className="p-3 text-start">{t('template.field.resource')}</TableHead>{times.map((time,index)=><TableHead className="p-3" key={time}>{definition.view==='matrix'?new Intl.DateTimeFormat(language,{weekday:'short',timeZone:'UTC'}).format(new Date(Date.UTC(2026,8,7+index))):format.time(time)}</TableHead>)}</TableRow></TableHeader><TableBody>{resources.map((resource,index)=><TableRow key={resource}><TableCell className="p-3 font-bold">{resource}</TableCell>{times.map((time,column)=><TableCell key={time} className="p-2"><Button className="w-full" disabled={disabled||index===1&&column===2} variant={document.values.resource===resource&&(document.values.startTime===time||document.values.scheduleDay===time)?'primary':'secondary'} onClick={()=>update({...document,values:{...document.values,resource,...(definition.view==='matrix'?{scheduleDay:time}:{startTime:time,endTime:time.replace(':00',':30')})}})}>{t(index===1&&column===2?'template.booked':'template.available')}</Button></TableCell>)}</TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>;
}
export function TemplateMatrix({document,format,definition}:TemplateEngineProps) {
 const {t}=useLocalization();
 const groups=[...new Set(document.rows.map(row=>String(row.resource)))];
 return <Card><CardHeader><CardTitle title="template.comparison"/></CardHeader><CardContent><TableContainer><Table className="w-full" bordered striped><TableHeader><TableRow><TableHead className="p-3 text-start">{t('template.field.resource')}</TableHead>{definition.stages.map(stage=><TableHead key={stage} className="p-3">{t(`template.status.${stage}`)}</TableHead>)}<TableHead className="p-3">{t('template.total')}</TableHead></TableRow></TableHeader><TableBody>{groups.map(group=><TableRow key={group}><TableCell className="p-3 font-bold">{group}</TableCell>{definition.stages.map(stage=><TableCell key={stage} className="p-3 text-end">{format.money(document.rows.filter(row=>row.resource===group&&row.status===stage).reduce((sum,row)=>sum+Number(row.amount),0))}</TableCell>)}<TableCell className="p-3 text-end font-bold">{format.money(document.rows.filter(row=>row.resource===group).reduce((sum,row)=>sum+Number(row.amount),0))}</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card>;
}
export function TemplateHierarchy({document,update,disabled}:TemplateEngineProps) {
 const {t}=useLocalization();const [selected,setSelected]=useState(String(document.rows[0]?.code??''));const depthOf=(code:string)=>{const seen=new Set<string>();let depth=0,parent=String(document.values[`parent.${code}`]??'');while(parent&&!seen.has(parent)){seen.add(parent);depth++;parent=String(document.values[`parent.${parent}`]??'');}return Math.min(depth,6);};
 return <Card><CardHeader><CardTitle title="template.hierarchy"/></CardHeader><CardContent className="grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]"><nav aria-label={t('template.hierarchy')} className="space-y-2">{document.rows.map((row,index)=><div key={String(row.code)} style={{paddingInlineStart:depthOf(String(row.code))*16}}><Button className="w-full justify-start" aria-pressed={selected===row.code} onClick={()=>setSelected(String(row.code))}>{row.name}</Button></div>)}</nav><div className="space-y-3"><Input label="template.field.name" disabled={disabled} value={String(document.rows.find(row=>row.code===selected)?.name??'')} onChange={event=>update({...document,rows:document.rows.map(row=>row.code===selected?{...row,name:event.target.value}:row)})}/><Select label="template.field.parent" disabled={disabled} value={String(document.values[`parent.${selected}`]??'')} options={[{value:'',label:'template.root'},...document.rows.filter(row=>row.code!==selected).map(row=>({value:String(row.code),label:String(row.name)}))]} onChange={event=>update({...document,values:{...document.values,[`parent.${selected}`]:event.target.value}})}/></div></CardContent></Card>;
}
export function TemplateImport({document,update,disabled}:TemplateEngineProps) {
 const {t}=useLocalization();const [data,setData]=useState<ReturnType<typeof parseCsv>|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[error,setError]=useState(''),[stage,setStage]=useState(1),[done,setDone]=useState(false);
 const columns=['code','name'];const missing=!data||columns.some(key=>mapping[key]===undefined||mapping[key]==='');
 const valid=data&&!missing&&mapping.code!==mapping.name?data.rows.every(row=>columns.every(key=>row[Number(mapping[key])]?.trim()))&&new Set(data.rows.map(row=>row[Number(mapping.code)]?.trim().toLowerCase())).size===data.rows.length:false;
 const upload=async(file:File)=>{setError('');setDone(false);setStage(1);setMapping({});try{if(file.size>2*1024*1024)throw Error('template.fileLimit');setData(parseCsv(await file.text()));}catch{setData(null);setError('template.invalidCsv');}};
 return <Card><CardHeader><CardTitle title="template.importFlow"/></CardHeader><CardContent className="space-y-4"><p>{t('template.importHelp')}</p><FilePicker label={t('template.chooseCsv')} accept=".csv" disabled={disabled} onFile={file=>void upload(file)}/>{error?<p role="alert">{t(error)}</p>:null}
  {data?<><Badge>{t('template.step',{step:stage})}</Badge><CardGrid columns={2}>{columns.map(key=><Select key={key} label={t(`template.field.${key}`)} aria-label={t(`template.field.${key}`)} value={mapping[key]??''} disabled={disabled||done} options={data.headers.map((label,index)=>({value:String(index),label}))} onChange={event=>{setMapping({...mapping,[key]:event.target.value});setStage(1);}}/>)}</CardGrid>
   <Button disabled={disabled||missing||done} onClick={()=>{setStage(2);setError(valid?'':'template.invalidRows');}}>{t('template.validate')}</Button>
   {stage>=2?<><p>{t('template.rowCount',{count:data.rows.length})}</p><TableContainer><Table className="w-full" bordered><TableHeader><TableRow>{columns.map(key=><TableHead className="p-2" key={key}>{t(`template.field.${key}`)}</TableHead>)}</TableRow></TableHeader><TableBody>{data.rows.slice(0,5).map((row,index)=><TableRow key={index}>{columns.map(key=><TableCell className="p-2" key={key}>{row[Number(mapping[key])]}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer><Button variant="primary" disabled={disabled||!valid||done} onClick={()=>{update({...document,rows:data.rows.map(row=>({code:row[Number(mapping.code)],name:row[Number(mapping.name)],date:'2026-09-09',amount:0,status:'requested'}))});setDone(true);setStage(3);}}>{t('template.confirmImport')}</Button></>:null}
   {done?<p role="status">{t('template.localImported')}</p>:null}
  </>:<EmptyState/>}
 </CardContent></Card>;
}
export function TemplateDocuments({document,update,disabled,communication=false}:TemplateEngineProps&{communication?:boolean}) {
 const {t}=useLocalization();const [text,setText]=useState('');
 return <Card><CardHeader><CardTitle title={communication?'template.conversation':'template.documents'}/></CardHeader><CardContent className="space-y-3">
  {communication?<><Textarea label="template.message" value={text} disabled={disabled} onChange={event=>setText(event.target.value)}/><Button disabled={disabled||!text.trim()} onClick={()=>{update({...document,lines:[...document.lines,{id:crypto.randomUUID(),description:text,quantity:0,price:0,debit:0,credit:0,result:'',reference:'',checked:false}]});setText('');}}>{t('template.addNote')}</Button></>:<FilePicker label={t('template.chooseDocument')} disabled={disabled} onFile={file=>update({...document,lines:[...document.lines,{id:crypto.randomUUID(),description:file.name,quantity:0,price:0,debit:0,credit:0,result:'',reference:'',checked:false}]})}/>}
  <DescriptionList layout="stacked" items={document.lines.map(line=>({id:line.id,label:communication?'template.message':'template.field.description',value:line.description}))}/><p className="text-sm text-[var(--text-muted)]">{t('template.documentHelp')}</p>
 </CardContent></Card>;
}
