// Writes fixtures. Run only against an isolated API data directory.
import assert from 'node:assert/strict';
import {loadPlaywright} from './harness.mjs';
import {audit} from './a11y.mjs';
const {chromium}=loadPlaywright(),browser=await chromium.launch({chromiumSandbox:false});
const errors=[];
async function login(username){const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await context.route('**/preferences',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({preferences:{sidebarPinned:true,reducedMotion:true,floatingWindows:false,openRecordsIn:'same-tab'}})}));await page.goto(process.env.E2E_DESKTOP??'http://127.0.0.1:3109');await page.getByPlaceholder('user1').fill(username);await page.locator('input[type=password]').fill(username);await page.locator('button[type=submit]').click();await page.locator('header').waitFor();return {context,page};}
async function worklist(page){await page.locator('header').waitFor();await page.keyboard.press('Control+k');await page.getByPlaceholder('Search pages, modules and actions…').fill('Customer Master');await page.getByRole('dialog').getByRole('button').filter({hasText:'Customer Master'}).first().click();await page.getByRole('button',{name:'Edit CUS-02401',exact:true}).waitFor();}
async function inbox(page){await worklist(page);await page.getByRole('button',{name:'Approval inbox',exact:true}).click();const panel=page.getByRole('region',{name:'Approval inbox',exact:true});await panel.getByText('Updating approvals…',{exact:true}).waitFor({state:'hidden'});return panel;}
async function confirm(page){await page.getByRole('button',{name:'Confirm approval action',exact:true}).click();await page.getByText('Updating approvals…',{exact:true}).locator('visible=true').waitFor({state:'hidden'});}
async function submit(page,id,resubmit=false){await worklist(page);await page.getByRole('button',{name:`Edit ${id}`,exact:true}).click();const panel=page.getByRole('region',{name:'Record approval',exact:true});await panel.getByRole('button',{name:'Refresh approvals'}).click();await panel.getByText('Updating approvals…',{exact:true}).waitFor({state:'hidden'});await panel.getByLabel('Approval comment').fill(resubmit?'Corrected and ready for another review':'Please review this customer');await panel.getByRole('button',{name:resubmit?'Resubmit saved record':'Submit for approval',exact:true}).click();await confirm(page);assert.equal(await panel.getByRole('alert').count(),0);await panel.getByText(/pending · Finance review/).waitFor();}
try{
 const admin=await login('admin'),requester=await login('user2'),finance=await login('user1');
 let panel=await inbox(admin.page);await panel.getByRole('button',{name:'Configure stages',exact:true}).click();await panel.getByLabel('1: enterprise-admin',{exact:true}).uncheck();await panel.getByRole('button',{name:'Add stage',exact:true}).click();await panel.getByLabel('Stage 2 name').fill('Final review');await panel.getByRole('button',{name:'Save approval stages',exact:true}).click();await confirm(admin.page);await admin.page.keyboard.press('Escape');
 for(const id of ['CUS-02401','CUS-02402'])await submit(requester.page,id);
 panel=await inbox(finance.page);await panel.getByRole('button',{name:'Select eligible rows on this page'}).click();await panel.getByLabel('Bulk decision comment').fill('Please confirm the customer details');await panel.getByRole('button',{name:'Request changes for selected'}).click();await confirm(finance.page);await panel.getByText('2 succeeded · 0 failed',{exact:true}).waitFor();await finance.page.keyboard.press('Escape');
 for(const id of ['CUS-02401','CUS-02402'])await submit(requester.page,id,true);
 panel=await inbox(finance.page);await panel.getByLabel(/^Approval ownership/).selectOption('assigned');await panel.getByRole('button',{name:'Select eligible rows on this page'}).click();await panel.getByLabel('Bulk decision comment').fill('Finance review complete');await panel.getByRole('button',{name:'Approve selected',exact:true}).click();await confirm(finance.page);await panel.getByText('2 succeeded · 0 failed',{exact:true}).waitFor();console.log('PASS configured stages, record submission, bulk change requests, resubmission and finance stage');
 panel=await inbox(admin.page);
 for(const [id,action] of [['CUS-02401','Approve selected'],['CUS-02402','Reject selected']]){await panel.getByLabel('Find approvals').fill(id);await panel.getByRole('button',{name:'Select eligible rows on this page'}).click();await panel.getByLabel('Bulk decision comment').fill(action==='Approve selected'?'Final approval granted':'Customer not eligible');await panel.getByRole('button',{name:action,exact:true}).click();await confirm(admin.page);await panel.getByText('1 succeeded · 0 failed',{exact:true}).waitFor();}
 panel=await inbox(requester.page);await panel.getByLabel(/^Approval status/).selectOption('');await panel.getByLabel(/^Approval ownership/).selectOption('mine');await panel.getByText(/approved · Final review/).waitFor();await panel.getByText(/rejected · Final review/).waitFor();await panel.getByText('Approval history for CUS-02401',{exact:true}).click();await panel.getByText('Final approval granted',{exact:true}).waitFor();await panel.getByText(/My approval notifications/).click();await panel.getByText(/CUS-02401: Approved/).waitFor();await panel.getByText(/CUS-02402: Rejected/).waitFor();await panel.getByRole('button',{name:'Mark notifications read'}).click();await panel.getByText('My approval notifications · Unread: 0',{exact:true}).waitFor();
 const violations=await audit(requester.page,{include:'[aria-label="Approval inbox"]'});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);assert.deepEqual(errors,[]);console.log('PASS final approval/rejection, requester filters, history, notifications, read receipts and accessibility');
 await requester.page.reload();panel=await inbox(requester.page);await panel.getByText('My approval notifications · Unread: 0',{exact:true}).waitFor();console.log('PASS notification read state survives reload');
}finally{await browser.close();}
