// Destructive fixtures: registered managed API only, never public demo data.
import assert from 'node:assert/strict';
import {loadPlaywright} from './harness.mjs';
const browser=await loadPlaywright().chromium.launch({chromiumSandbox:false});
try{
 const context=await browser.newContext({viewport:{width:1700,height:1100}}),page=await context.newPage();page.setDefaultTimeout(30000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/preferences',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({preferences:{sidebarPinned:true,reducedMotion:true,floatingWindows:false,openRecordsIn:'same-tab'},canManage:true})}));
 await page.goto(process.env.E2E_DESKTOP??'http://127.0.0.1:3109');await page.getByPlaceholder('user1').fill('admin');await page.locator('input[type=password]').fill('admin');await page.locator('button[type=submit]').click();
 async function open(id){await page.locator('header').first().waitFor();await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog');await dialog.locator('input').first().fill(id);await dialog.locator('button.group').first().click();}
 async function worklist(){await open('customer-master');await page.getByRole('button',{name:'Edit CUS-02401',exact:true}).waitFor();}
 async function importer(){await worklist();await page.getByRole('button',{name:'More worklist actions',exact:true}).click();await page.getByRole('button',{name:'Import records',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Import Customer Master',exact:true});await dialog.getByText('Loading import…',{exact:true}).waitFor({state:'hidden'});return dialog;}
 async function inbox(){await worklist();await page.getByRole('button',{name:'Approval inbox',exact:true}).click();const panel=page.getByRole('region',{name:'Approval inbox',exact:true});await panel.getByText('Updating approvals…',{exact:true}).waitFor({state:'hidden'});return panel;}
 await worklist();await page.getByRole('button',{name:'Edit CUS-02401',exact:true}).click();let name=page.getByRole('textbox',{name:/Legal name/});await name.fill('Durable form draft');await page.getByText('Recovery draft saved · record has unsaved changes',{exact:true}).waitFor();
 await page.reload();await worklist();await page.getByRole('button',{name:'Edit CUS-02401',exact:true}).click();await page.getByRole('button',{name:'Restore draft',exact:true}).waitFor();name=page.getByRole('textbox',{name:/Legal name/});assert.notEqual(await name.inputValue(),'Durable form draft');await page.getByRole('button',{name:'Restore draft',exact:true}).click();assert.equal(await name.inputValue(),'Durable form draft');console.log('PASS form draft survives reload and restores only after explicit choice');
 // Reload abandons the mounted editor without invoking explicit close/discard.
 await page.reload();let dialog=await importer();const csv='customerCode,Company,customerType,contactName,email,address1,city\r\nDRAFT-CSV,Mapping sample,Corporate,Demo,mail@example.test,Street,Dubai';
 const upload=()=>dialog.getByLabel('Upload CSV file').setInputFiles({name:'draft.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
 await upload();await dialog.getByLabel(/^Legal name/).selectOption('1');await dialog.getByText(/Draft saved:/).waitFor();await page.reload();dialog=await importer();await dialog.getByRole('button',{name:'Restore draft',exact:true}).waitFor();assert.equal(await dialog.getByRole('button',{name:'Restore draft',exact:true}).isEnabled(),false);await upload();await dialog.getByRole('button',{name:'Restore draft',exact:true}).click();assert.equal(await dialog.getByLabel(/^Legal name/).inputValue(),'1');await dialog.getByText('Mapping sample',{exact:true}).waitFor();console.log('PASS import mapping survives reload, requires matching CSV headers and preserves manual selection');
 await page.reload();let panel=await inbox();await panel.getByLabel('Bulk decision comment').fill('Durable approval comment');await panel.getByText(/Draft saved:/).waitFor();await page.reload();panel=await inbox();await panel.getByRole('button',{name:'Restore draft',exact:true}).waitFor();assert.equal(await panel.getByLabel('Bulk decision comment').inputValue(),'');await panel.getByRole('button',{name:'Restore draft',exact:true}).click();assert.equal(await panel.getByLabel('Bulk decision comment').inputValue(),'Durable approval comment');
 assert.equal(await page.evaluate(()=>Object.values(localStorage).some(value=>value.includes('Durable approval comment')||value.includes('Durable form draft')||value.includes('Mapping sample'))),false);
 await page.reload();panel=await inbox();await panel.getByRole('button',{name:'Discard draft',exact:true}).click();await panel.getByRole('button',{name:'Restore draft',exact:true}).waitFor({state:'hidden'});await page.reload();panel=await inbox();assert.equal(await panel.getByRole('button',{name:'Restore draft',exact:true}).count(),0);console.log('PASS approval comment survives reload, stays outside browser storage and explicit discard persists');
 await page.reload();await open('preferences');await page.getByRole('tab',{name:'Preference policies'}).click();const policy=page.locator('[data-draft-policy]');await policy.getByRole('button',{name:'Save draft policy'}).waitFor();await policy.getByLabel('Retention in days (1–30)').fill('1');await policy.getByLabel('Excluded field names or paths').fill('legalName\ncomment');await policy.getByRole('button',{name:'Save draft policy'}).click();await policy.getByText('Draft policy saved.',{exact:true}).waitFor();await page.screenshot({path:'/tmp/drafts-policy.png'});
 const stored=await page.evaluate(async(api)=>{const r=await fetch(api+'/records/'+encodeURIComponent(JSON.stringify(['nexora','form:customer-master:CUS-02401'])),{headers:{Authorization:'Bearer '+localStorage.getItem('nexora-session-token')}});return r.json();},process.env.E2E_API??'http://127.0.0.1:3330');assert.equal(stored.draft.values.legalName,undefined);
 await policy.getByRole('switch',{name:'Store recovery drafts'}).click();await policy.getByRole('button',{name:'Save draft policy'}).click();await policy.getByText('Draft policy saved.',{exact:true}).waitFor();await page.reload();await worklist();await page.getByRole('button',{name:'Edit CUS-02401',exact:true}).click();await page.getByText(/Draft storage is disabled by your tenant administrator/).first().waitFor();assert.equal(await page.getByRole('button',{name:'Restore draft',exact:true}).count(),0);
 assert.deepEqual(errors,[]);console.log('PASS administrator retention/exclusion controls, retroactive field removal and disabled storage purge');
}finally{await browser.close();}
