// Managed, isolated API fixtures only.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {loadPlaywright} from './harness.mjs';
import {audit} from './a11y.mjs';
const browser=await loadPlaywright().chromium.launch({chromiumSandbox:false});
try{
 const context=await browser.newContext({viewport:{width:1700,height:1100}}),page=await context.newPage(),errors=[];page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/preferences',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({preferences:{sidebarPinned:true,reducedMotion:true,floatingWindows:false,openRecordsIn:'same-tab'}})}));
 await page.goto(process.env.E2E_DESKTOP??'http://127.0.0.1:3109');await page.getByPlaceholder('user1').fill('admin');await page.locator('input[type=password]').fill('admin');await page.locator('button[type=submit]').click();await page.locator('header').first().waitFor();
 const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex'),headers=['Company'];
 const result=await page.evaluate(async({api,hash,headersHash})=>{
  const headers={Authorization:'Bearer '+localStorage.getItem('nexora-session-token'),'Content-Type':'application/json','X-Product-Id':'nexora'};
  const statuses=[];for(const record of ['CUS-02401','PRIVATE-MISSING-RECORD'])statuses.push((await fetch(api+'/records/'+encodeURIComponent(JSON.stringify(['nexora','form:customer-master:'+record]))+'/draft',{method:'PUT',headers,body:JSON.stringify({version:0,baseVersion:0,operationId:crypto.randomUUID(),values:{legalName:'PRIVATE DRAFT CONTENT'}})})).status);
  for(const [kind,recordId,context,data] of [['approval','inbox',hash,{comment:'Private approval comment'}],['import','mapping',headersHash,{mapping:{legalName:'0'}}]])statuses.push((await fetch(api+'/drafts',{method:'POST',headers,body:JSON.stringify({kind,pageId:'customer-master',recordId,action:'draft',version:0,operationId:crypto.randomUUID(),values:{schemaVersion:1,context,data}})})).status);
  const listing=await fetch(api+'/draft-center',{method:'POST',headers,body:JSON.stringify({action:'list'})});return {statuses,listing:await listing.json()};
 },{api:process.env.E2E_API??'http://127.0.0.1:3330',hash:hash([0,[]]),headersHash:hash(headers)});
 assert.deepEqual(result.statuses,[200,200,200,200]);assert.equal(result.listing.total,4);assert.ok(!JSON.stringify(result.listing).includes('PRIVATE'));assert.ok(!JSON.stringify(result.listing).includes('Private approval'));
 async function openCenter(){await page.locator('header').first().waitFor();await page.keyboard.press('Control+k');const dialog=page.getByRole('dialog');await dialog.locator('input').first().fill('draft-recovery');await dialog.locator('button.group').first().click();await page.locator('[data-draft-center]').getByText('CUS-02401',{exact:true}).waitFor();}
 await openCenter();let center=page.locator('[data-draft-center]');assert.equal(await center.locator('tbody tr').count(),4);const hidden=center.locator('tr').filter({hasText:'Record details hidden because access is unavailable'});assert.equal(await hidden.getByRole('button',{name:'Open draft',exact:true}).isEnabled(),false);
 assert.deepEqual((await audit(page,{include:'[data-draft-center]'})).filter(v=>['critical','serious'].includes(v.impact)),[]);await page.screenshot({path:'/tmp/draft-center.png'});
 await center.getByLabel('Search by page or record ID').fill('CUS-02401');await page.waitForFunction(()=>document.querySelectorAll('[data-draft-center] tbody tr').length===1);await center.getByRole('button',{name:'Open draft',exact:true}).click();await page.getByRole('button',{name:'Restore draft',exact:true}).click();assert.equal(await page.getByRole('textbox',{name:/Legal name/}).inputValue(),'PRIVATE DRAFT CONTENT');console.log('PASS center metadata privacy, filters, unavailable-record controls, accessibility and form navigation');
 await page.reload();await openCenter();center=page.locator('[data-draft-center]');await center.getByLabel('Draft type').selectOption('approval');await center.getByRole('cell',{name:'Approval comment',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('[data-draft-center] tbody tr').length===1);await center.getByRole('button',{name:'Open draft',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Restore draft',exact:true}).click();assert.equal(await dialog.getByLabel('Bulk decision comment').inputValue(),'Private approval comment');await page.keyboard.press('Escape');
 await center.getByLabel('Draft type').selectOption('import');await center.getByRole('cell',{name:'Import mapping',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('[data-draft-center] tbody tr').length===1);await center.getByRole('button',{name:'Open draft',exact:true}).click();dialog=page.getByRole('dialog',{name:'Import Customer Master',exact:true});await dialog.getByRole('button',{name:'Restore draft',exact:true}).waitFor();assert.equal(await dialog.getByRole('button',{name:'Restore draft',exact:true}).isEnabled(),false);await dialog.getByLabel('Upload CSV file').setInputFiles({name:'mapping.csv',mimeType:'text/csv',buffer:Buffer.from('Company\nDraft company')});await dialog.getByRole('button',{name:'Restore draft',exact:true}).click();assert.equal(await dialog.getByLabel(/^Legal name/).inputValue(),'0');await page.keyboard.press('Escape');
 await center.getByRole('button',{name:'Discard draft',exact:true}).click();await center.getByText('No saved drafts match these filters.').waitFor();await page.reload();await openCenter();await center.getByLabel('Draft type').selectOption('import');await center.getByText('No saved drafts match these filters.').waitFor();assert.deepEqual(errors,[]);console.log('PASS open approval/import workflows and durable discard from the center');
}finally{await browser.close();}
