import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';import {loadPlaywright} from './harness.mjs';const browser=await loadPlaywright().chromium.launch({chromiumSandbox:false}),dir=process.env.E2E_ARTIFACTS??'/tmp/identity-browser';mkdirSync(dir,{recursive:true});
try{const page=await browser.newPage({viewport:{width:1600,height:1000}});page.setDefaultTimeout(25000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.E2E_DESKTOP??'http://127.0.0.1:3109');await page.locator('input').first().fill('admin');await page.locator('input[type=password]').fill('admin');await page.keyboard.press('Enter');await page.locator('header').first().waitFor();const root=page.locator('[data-identity-library]:visible');async function open(id){await page.keyboard.press('Control+k');const d=page.getByRole('dialog');await d.locator('input').first().fill(id);await d.locator('button.group').first().click();await root.getByLabel('Selected patient').waitFor();}
async function start(){await root.getByLabel('Selected patient').selectOption('DEMO-P1');await root.getByLabel('Demo: patient permission and selected identity reviewed').check();await root.getByRole('button',{name:'Start demo identity request'}).click();await root.getByRole('button',{name:'Simulate reader result'}).waitFor();}
async function simulate(scenario,status){await root.getByLabel('API demonstration scenario').selectOption(scenario);const response=page.waitForResponse(r=>r.url().endsWith('/identity-devices')&&r.request().postDataJSON()?.action==='simulate');await root.getByRole('button',{name:'Simulate reader result'}).click();const r=await response;assert.equal(r.status(),200);const a=await r.json();assert.equal(a.authenticated,false);assert.equal(a.status,status);await root.getByText(status==='demo-match'?'Demo match · not authenticated':'Demo document expired · review required',{exact:true}).first().waitFor();}
await open('identity-card-readers');await root.getByLabel('Identity reader / method').selectOption('demo-eid');await start();await simulate('match','demo-match');await root.getByText('DEMO-DOC-001',{exact:true}).waitFor();await page.screenshot({path:dir+'/eid.png'});
await open('passport-scanner');await start();await simulate('expired','demo-expired-document');await page.screenshot({path:dir+'/passport.png'});
await open('patient-biometric-verification');await root.getByLabel('Selected patient').selectOption('DEMO-P1');assert.equal(await root.getByRole('button',{name:'Start demo identity request'}).isDisabled(),true);await root.getByRole('button',{name:'Route to manual review'}).click();await root.getByText('Manual review required · not authenticated',{exact:true}).first().waitFor();await root.getByLabel('Enable biometric demonstration').check();await root.getByRole('button',{name:'Save identity policy'}).click();await start();await simulate('match','demo-match');assert.equal(await root.locator('img').count(),0);await page.screenshot({path:dir+'/biometric.png'});
for(const lang of ['ar','hi','ml']){await page.keyboard.press('Control+k');const d=page.getByRole('dialog');await d.locator('input').first().fill('preferences');await d.locator('button.group').first().click();await page.getByRole('tab').filter({hasText:/Language & help|اللغة والمساعدة|भाषा और सहायता|ഭാഷയും സഹായവും/}).click();await page.locator('[data-tour=prefs-lang] select:visible').selectOption(lang);await page.waitForFunction(l=>document.documentElement.lang===l,lang);await page.keyboard.press('Control+k');const search=page.getByRole('dialog');await search.locator('input').first().fill('identity-card-readers');await search.locator('button.group').first().click();await root.waitFor();assert.ok(!/identity\.[A-Za-z]/.test(await root.innerText()));await page.screenshot({path:dir+'/'+lang+'.png'});}
assert.deepEqual(errors,[]);console.log('PASS three identity pages, EID synthetic document, expired passport, biometric opt-in, manual fallback, authenticated:false, four languages; isolated demo API and Chromium. No real device, biometric capture or authentication.');
}catch(e){const p=browser.contexts()[0]?.pages()[0];if(p)await p.screenshot({path:dir+'/failure.png'});throw e;}finally{await browser.close();}
